import { BarChart, Bar, CartesianGrid, XAxis, YAxis, Tooltip, ResponsiveContainer, LineChart, Line, ReferenceLine } from 'recharts';
import type {AgeSex, Distribution, HistoryPoint} from './types';
import {count} from './data';
const chartMargins={top:12,right:15,bottom:10,left:0};
export function HistoryChart({rows,estimate=false}: {rows:HistoryPoint[];estimate?:boolean}) {
  const points=rows.map(row=>({...row,year:Number(row.period)}));
  return <div className="pop-history-chart" role="img" aria-label={`${estimate?'Estimativas anuais':'População por Censo'}, em pessoas. Cada ponto representa um período publicado. Consulte a tabela acessível abaixo.`}><ResponsiveContainer width="100%" height="100%"><LineChart data={points} margin={chartMargins}><CartesianGrid vertical={false} strokeDasharray="3 3"/><XAxis dataKey="year" type="number" domain={['dataMin','dataMax']} ticks={estimate?undefined:points.map(p=>p.year)} tick={{fontSize:11}} allowDecimals={false}/><YAxis width={62} tickFormatter={v=>count(v)} tick={{fontSize:11}} domain={['auto','auto']}/><Tooltip formatter={v=>[`${count(Number(v))} pessoas`,estimate?'Estimativa':'Censo']} labelFormatter={v=>`Referência: ${v}`}/><Line name={estimate?'Estimativa':'Censo'} dataKey="value" type="linear" stroke={estimate?'#b58132':'#26765c'} strokeWidth={3} dot={{r:4}} activeDot={{r:6}} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>;
}
export function AgePyramid({rows}: {rows:AgeSex[]}) {
  const data=[...rows].reverse().map(row=>({...row,men:-row.male,women:row.female}));
  const max=Math.ceil(Math.max(...rows.flatMap(row=>[row.male,row.female]))/100)*100;
  return <><div className="pop-pyramid-heading"><span>← Homens</span><span>Faixa etária</span><span>Mulheres →</span></div><div className="pop-pyramid" role="img" aria-label="Pirâmide etária: homens à esquerda e mulheres à direita, em pessoas. As faixas etárias estão no eixo vertical e na tabela abaixo."><ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={data} stackOffset="sign" margin={{top:8,right:10,bottom:8,left:3}}><CartesianGrid horizontal={false} strokeDasharray="3 3"/><XAxis type="number" domain={[-max,max]} tickFormatter={v=>count(Math.abs(v))} tick={{fontSize:10}}/><YAxis type="category" dataKey="ageGroup" width={48} tick={{fontSize:11}}/><ReferenceLine x={0} stroke="#6c8779"/><Tooltip formatter={(value,name)=>[`${count(Math.abs(Number(value)))} pessoas`,name]} labelFormatter={v=>`Idade: ${v}`}/><Bar dataKey="men" name="Homens (esquerda)" fill="#26765c" stackId="sex" isAnimationActive={false}/><Bar dataKey="women" name="Mulheres (direita)" fill="#b38a4d" stackId="sex" isAnimationActive={false}/></BarChart></ResponsiveContainer></div></>;
}
export function DistributionChart({data}: {data:Distribution}) {
  return <div className="pop-distribution-chart" style={{height:Math.max(145,data.rows.length*48)}} role="img" aria-label="Gráfico de barras horizontais em pessoas. Categorias e valores também estão na tabela abaixo."><ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={data.rows} margin={chartMargins}><CartesianGrid horizontal={false} strokeDasharray="3 3"/><XAxis type="number" tickFormatter={v=>count(v)} tick={{fontSize:10}}/><YAxis type="category" dataKey="category" width={75} tick={{fontSize:11}}/><Tooltip formatter={v=>[`${count(Number(v))} pessoas`,'Quantidade']}/><Bar dataKey="value" fill="#398169" radius={[0,4,4,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div>;
}
