import { useEffect, useState } from 'react';
import { ArrowDownToLine, Users, Info } from 'lucide-react';
import type { PopulationData } from './types';
import {loadPopulation, narratives, count, percent, date, populationUrl} from './data';
import {MetricCard, Section, SourceNote, DistributionTable, DownloadLink, BoundaryMap} from './PopulationComponents';
import {HistoryChart, AgePyramid, DistributionChart} from './PopulationCharts';
import './population.css';
export default function PopulationPage() {
  const [data,setData]=useState<PopulationData>(),[error,setError]=useState(''),[retry,setRetry]=useState(0);
  useEffect(()=>{const controller=new AbortController();setError('');setData(undefined);loadPopulation(controller.signal).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[retry]);
  if(error) return <section className="panel" role="alert"><h2>População indisponível</h2><p>{error}</p><button onClick={()=>setRetry(n=>n+1)}>Tentar novamente</button></section>;
  if(!data) return <div role="status" className="loading">Carregando o retrato demográfico…<div className="skeleton"/></div>;
  const source=(ids:string[])=>data.sources.filter(item=>ids.includes(item.id));
  const texts=narratives(data);
  const growth=data.growth;
  return <div className="population-page">
    <div className="pop-intro"><div><span className="eyebrow"><Users size={13}/> POPULAÇÃO E TERRITÓRIO</span><h2>As pessoas que formam Turvo.</h2><p>{texts.estimate}</p></div><DownloadLink path="population.json">Baixar dados de População</DownloadLink></div>
    <nav className="pop-jump" aria-label="Seções de População">{[['pop-current','Retrato atual'],['pop-history','Evolução'],['pop-age','Idade'],['pop-profile','Perfil'],['pop-race','Cor ou raça'],['pop-place','Urbano / rural'],['pop-homes','Domicílios'],['pop-territory','Território'],['pop-sources','Fontes']].map(([id,label])=><button key={id} onClick={()=>document.getElementById(id)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}>{label}</button>)}</nav>
    {data.collection.failures.length>0&&<div className="notice" role="status">A última coleta teve falha. Exibimos o último snapshot validado, de {date(data.collection.lastSuccessAt)}. Tentativa: {date(data.collection.attemptedAt)}.<details><summary>Ver relatório</summary>{data.collection.failures.map(f=><p key={f}>{f}</p>)}</details></div>}
    <section id="pop-current" className="pop-current"><div className="section-title"><h2>Retrato atual</h2><span>Referências distintas, conceitos identificados</span></div><div className="cards">{['population-estimate','population-census','population-density','territorial-area'].map(id=><MetricCard key={id} metric={data.summary[id]} source={source([data.summary[id].sourceId])[0]}/>)}</div><p className="pop-callout"><Info size={16}/> Censo conta a população; estimativa é um cálculo anual do IBGE. A densidade refere-se a 2022 e mantém a área utilizada naquele Censo.</p></section>
    <Section id="pop-history" eyebrow="01 / EVOLUÇÃO POPULACIONAL" title="Evolução da população de Turvo" description="Somente períodos censitários publicados. Os pontos não representam estimativas e não há valores interpolados.">
      <div className="pop-history-layout"><div><HistoryChart rows={data.populationHistory.rows}/><details className="pop-accessible"><summary>Ver população por Censo em tabela</summary><div className="table-wrap"><table><caption>População residente conforme publicação de cada Censo</caption><thead><tr><th scope="col">Censo</th><th scope="col">Pessoas</th><th scope="col">Tabela / Fonte</th></tr></thead><tbody>{data.populationHistory.rows.map(row=><tr key={row.period}><th scope="row">{row.period}</th><td>{count(row.value)}</td><td><a href={source([row.sourceId])[0].url} target="_blank" rel="noreferrer">IBGE · {source([row.sourceId])[0].table}</a></td></tr>)}</tbody></table></div></details></div><div className="pop-growth"><span className="eyebrow">{growth.from} → {growth.to} · BASE COMPATIBILIZADA</span><strong>{growth.absoluteChange>0?'+':growth.absoluteChange<0?'−':''}{percent(Math.abs(growth.percentChange))}</strong><p>{texts.growth}</p><dl><div><dt>Variação absoluta oficial</dt><dd>{count(growth.absoluteChange)} pessoas</dd></div><div><dt>Taxa geométrica oficial</dt><dd>{percent(growth.annualGeometricRate)} ao ano</dd></div><div><dt>Base 2010 compatibilizada¹</dt><dd>{count(growth.compatibleBaseline)} pessoas</dd></div></dl></div></div>
      <p className="pop-method">¹ Base compatibilizada derivada da população 2022 menos a variação absoluta oficial da tabela 4709. O Censo 2010 na tabela histórica registra {count(data.populationHistory.rows.find(row=>row.period==='2010')!.value)} pessoas; não é a mesma base territorial. O gráfico preserva a publicação de cada Censo, e as variações acima usam somente a comparação compatibilizada. Mudanças territoriais afetam a leitura da série.</p>
      <SourceNote sources={source(data.populationHistory.sourceIds)}/><SourceNote sources={source(growth.sourceIds)} reference="2010–2022"/>
      <details className="pop-estimates"><summary>Estimativas anuais · série separada dos Censos</summary><p>Estimativas em 1º de julho, sujeitas a revisões e mudanças territoriais. Somente anos publicados. Não comparamos esta curva diretamente como crescimento entre Censos.</p><HistoryChart rows={data.estimateHistory.rows} estimate/><div className="table-wrap"><table><caption>Estimativas populacionais · pessoas</caption><thead><tr><th>Ano</th><th>Estimativa</th></tr></thead><tbody>{data.estimateHistory.rows.map(row=><tr key={row.period}><th scope="row">{row.period}</th><td>{count(row.value)}</td></tr>)}</tbody></table></div><SourceNote sources={source(data.estimateHistory.sourceIds)}/></details>
    </Section>
    <Section id="pop-age" eyebrow="02 / ESTRUTURA DA POPULAÇÃO" title="Pirâmide etária" description={`Homens à esquerda, mulheres à direita. Quantidades de pessoas em ${data.ageSex.reference}; categorias de sexo conforme o IBGE.`}>
      <p className="pop-narrative">{texts.older}</p><AgePyramid rows={data.ageSex.rows}/><details className="pop-accessible"><summary>Ver idade e sexo em tabela acessível</summary><div className="table-wrap"><table><caption>População por grupos etários agregados · {data.ageSex.reference}</caption><thead><tr><th scope="col">Idade</th><th scope="col">Homens</th><th scope="col">Mulheres</th><th scope="col">Total</th><th scope="col">% do total</th></tr></thead><tbody>{data.ageSex.rows.map(row=><tr key={row.ageGroup}><th scope="row">{row.ageGroup}</th><td>{count(row.male)}</td><td>{count(row.female)}</td><td>{count(row.total)}</td><td>{percent(row.percent)}</td></tr>)}</tbody></table></div></details><SourceNote sources={source(data.ageSex.sourceIds)} reference={data.ageSex.reference}/>
    </Section>
    <Section id="pop-profile" eyebrow="03 / PERFIL DEMOGRÁFICO" title="Sexo e indicadores demográficos" description="Os indicadores oficiais consideram o total de cor ou raça. Percentuais de sexo são calculados sobre o total da própria tabela.">
      <div className="pop-distribution-layout"><div><DistributionChart data={data.sex}/><DistributionTable data={data.sex}/><SourceNote sources={source(data.sex.sourceIds)} reference={data.sex.reference}/></div><div><div className="pop-small-cards">{data.demographicIndicators.indicators.map(metric=><MetricCard key={metric.id} metric={metric} source={source([metric.sourceId])[0]}/>)}</div></div></div><p className="pop-narrative">{texts.aging}</p><details className="pop-accessible"><summary>Ver indicadores demográficos de 2010 e 2022</summary><div className="table-wrap"><table><caption>Valores oficiais da tabela 9756</caption><thead><tr><th>Ano</th><th>Idade mediana (anos)</th><th>Índice de envelhecimento (60+ / 100 de 0–14)</th><th>Razão de sexo (homens / 100 mulheres)</th></tr></thead><tbody>{data.demographicIndicators.rows.map(row=><tr key={row.period}><th scope="row">{row.period}</th><td>{count(row.medianAge)}</td><td>{count(row.agingIndex,2)}</td><td>{count(row.sexRatio,2)}</td></tr>)}</tbody></table></div></details><SourceNote sources={source(data.demographicIndicators.sourceIds)} reference="2010 e 2022"/>
    </Section>
    <Section id="pop-race" eyebrow="04 / IDENTIFICAÇÃO ÉTNICO-RACIAL" title="Cor ou raça" description="Categorias oficiais do Censo 2022, sem alteração de nomenclatura. Quantidades e percentuais do total considerado."><div className="pop-distribution-layout"><DistributionChart data={data.race}/><DistributionTable data={data.race}/></div><p className="pop-method">A categoria Indígena neste gráfico é o recorte de cor ou raça. Não representa o universo ampliado de indígenas que inclui o quesito “se considera indígena”.</p><SourceNote sources={source(data.race.sourceIds)} reference={data.race.reference}/></Section>
    <Section id="pop-place" eyebrow="05 / SITUAÇÃO DO DOMICÍLIO" title="População urbana e rural" description="Resultados municipais do Censo 2022, tabela 9923. A classificação corresponde à situação do domicílio na pesquisa."><div className="pop-distribution-layout"><DistributionChart data={data.urbanRural}/><DistributionTable data={data.urbanRural}/></div><SourceNote sources={source(data.urbanRural.sourceIds)} reference={data.urbanRural.reference}/></Section>
    <Section id="pop-homes" eyebrow="06 / DOMICÍLIOS" title="Onde a população vive" description="Recorte de domicílios particulares permanentes ocupados; esta seção não inclui indicadores de saneamento."><div className="pop-household-cards">{data.households.indicators.map(metric=><MetricCard key={metric.id} metric={metric} source={source([metric.sourceId])[0]}/>)}</div><p className="pop-method">O universo desta tabela contém {count(data.households.residents)} moradores. Ele difere da população residente total, pois exclui outras espécies de domicílio. A média apresentada é o valor oficial arredondado.</p><SourceNote sources={source(data.households.sourceIds)} reference={data.households.reference}/></Section>
    <Section id="pop-territory" eyebrow="07 / TERRITÓRIO" title="Turvo no Paraná" description="Um contorno informativo do município, obtido da malha oficial e servido localmente."><div className="pop-territory-layout"><BoundaryMap boundary={data.territory.geometry}/><div><dl><div><dt>Município / UF</dt><dd>{data.municipality.name} / {data.municipality.state}</dd></div><div><dt>Código IBGE</dt><dd>{data.municipality.code}</dd></div><div><dt>Área territorial · {data.summary['territorial-area'].reference}</dt><dd>{count(data.summary['territorial-area'].value,3)} km²</dd></div><div><dt>Região geográfica</dt><dd>{data.territory.region}</dd></div><div><dt>Região imediata / intermediária</dt><dd>{data.territory.immediateRegion} / {data.territory.intermediateRegion}</dd></div></dl><p className="pop-method">Malha de {data.territory.geometryReference}, qualidade intermediária do IBGE. A edição do mapa difere da área anual mais recente: não use o desenho para medições ou limites cadastrais.</p></div></div><DownloadLink path="population/turvo.geojson">Contorno municipal · GeoJSON</DownloadLink><SourceNote sources={source(data.territory.sourceIds)}/></Section>
    <Section id="pop-sources" eyebrow="08 / TRANSPARÊNCIA" title="Fontes e metodologia" description="Toda visualização mantém pesquisa, tabela, referência e coleta. Dados brutos, consultas e transformações podem ser auditados."><div className="table-wrap"><table><caption>Fontes oficiais verificadas para Turvo · IBGE 4127965</caption><thead><tr><th>Pesquisa / conjunto</th><th>Tabela / indicador</th><th>Referências</th><th>Coleta</th><th>Consulta / auditoria</th></tr></thead><tbody>{data.sources.map(item=><tr key={item.id}><th scope="row">IBGE · {item.research}<br/>{item.title}</th><td>{item.table??item.indicator??'API'}</td><td>{item.periods.length>6?`${item.periods[0]}–${item.periods[item.periods.length-1]} (anos publicados)`:item.reference}</td><td>{date(item.collectedAt)}</td><td><a href={item.url} target="_blank" rel="noreferrer">Fonte oficial</a><br/>{item.rawPath&&<a href={populationUrl(item.rawPath)} download>Resposta bruta</a>}</td></tr>)}</tbody></table></div><div className="pop-methodology"><h3>Como interpretar os dados</h3><p>Censo e estimativa são conjuntos separados. Cada referência identifica o período do dado; a data da coleta indica somente quando a consulta foi realizada. Contagens e percentuais do mesmo conjunto são conferidos entre si; universos de pesquisas diferentes não são forçados a coincidir.</p><p>No SIDRA, “-” representa zero absoluto e é convertido explicitamente segundo a convenção oficial, preservada no arquivo bruto. “X” (inibido), “..” (não aplicável) e “...” (indisponível) nunca são convertidos em zero. Períodos sem informação para Turvo não aparecem no gráfico.</p><p>As consultas rodam no ETL, fora do navegador. Se alguma fonte ou validação requerida falhar, preservamos integralmente o último snapshot validado. A verificação é semanal quando a automação estiver ativada; os dados mudam conforme a periodicidade do IBGE.</p></div><SourceNote sources={data.sources}/><div className="pop-downloads"><h3><ArrowDownToLine size={18}/> Baixar dados de População</h3><div><DownloadLink path="population.json">JSON completo e metadados</DownloadLink><DownloadLink path="population-history.csv">Evolução censitária · CSV</DownloadLink><DownloadLink path="population-estimates.csv">Estimativas · CSV</DownloadLink><DownloadLink path="population-age-sex.csv">Idade e sexo · CSV</DownloadLink><DownloadLink path="population-race.csv">Cor ou raça · CSV</DownloadLink></div></div></Section>
  </div>;
}
