import {useEffect,useState} from 'react';
import {BriefcaseBusiness,Download} from 'lucide-react';
import type {EmploymentData} from './types';
import {loadEmployment,narratives,dataUrl,integer,signed,money,period,date} from './data';
import {Section,Metric,SourceNote,MonthlyTable,CategoryTable,Comparison,Methodology} from './EmploymentComponents';
import {MonthlyChart,StockChart} from './EmploymentCharts';
import './employment.css';
export default function EmploymentPage({comparisonOnly=false}:{comparisonOnly?:boolean}){
 const [data,setData]=useState<EmploymentData>(),[error,setError]=useState(''),[retry,setRetry]=useState(0),[order,setOrder]=useState<'balance'|'admissions'>('balance');
 useEffect(()=>{const controller=new AbortController();setData(undefined);setError('');loadEmployment(controller.signal).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[retry]);
 if(error)return <section className="panel" role="alert"><h2>Trabalho e Emprego indisponível</h2><p>{error}</p><button onClick={()=>setRetry(n=>n+1)}>Tentar novamente</button></section>;
 if(!data)return <div role="status" className="loading">Carregando Trabalho e Emprego…<div className="skeleton"/></div>;
 const r=data.rais,c=data.caged,last=c.monthly.at(-1),text=narratives(data),raisSource=data.sources.find(s=>s.id==='rais'),cagedSource=data.sources.find(s=>s.id==='caged');
 const warning=data.collection.failures.length>0&&<div className="notice" role="status">A última tentativa teve falhas. Dados anteriores validados foram preservados.<details><summary>Relatório da coleta · {date(data.collection.attemptedAt)}</summary>{data.collection.failures.map(f=><p key={f}>{f}</p>)}</details></div>;
 if(comparisonOnly)return <div className="employment-page">{warning}<Comparison data={data}/></div>;
 return <div className="employment-page"><div className="emp-intro"><div><span className="eyebrow"><BriefcaseBusiness size={15}/> TRABALHO EM NÚMEROS</span><h2>O retrato anual.<br/>O movimento de cada mês.</h2><p>Vínculos formais, admissões e desligamentos. Conheça as duas bases oficiais e o período de cada informação.</p></div><a className="emp-download" href={dataUrl('employment.json')} download><Download size={16}/> Baixar dados de Trabalho e Emprego</a></div><nav className="emp-jump" aria-label="Seções de Trabalho e Emprego">{[['emp-summary','Panorama'],['emp-monthly','Movimentação'],['emp-sectors','Setores'],['emp-rais','Estrutura RAIS'],['emp-occupations','Ocupações'],['emp-salary','Remuneração'],['emp-comparison','Comparação'],['emp-sources','Fontes']].map(([id,label])=><button key={id} onClick={()=>document.getElementById(id)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}>{label}</button>)}</nav>{warning}
 <section id="emp-summary"><div className="section-title"><h2>Trabalho em números</h2><span>RAIS {r.reference??'indisponível'} · CAGED {c.latestReference??'indisponível'}</span></div><div className="cards emp-cards"><Metric title="Vínculos formais" value={integer(r.stock?.value)} unit="Ativos em 31 de dezembro" reference={r.reference} source="RAIS"/><Metric title="Saldo no mês" value={signed(last?.balance)} unit="Admissões − desligamentos" reference={c.latestReference} source="CAGED"/><Metric title="Saldo no ano" value={signed(c.yearToDate?.balance)} unit={c.yearToDate?.status==='available'?`${c.yearToDate.from} → ${c.yearToDate.to}`:'Janela ainda não disponível'} reference={c.latestReference} source="CAGED"/><Metric title="Saldo em 12 meses" value={signed(c.rolling12Months?.balance)} unit={c.rolling12Months?.status==='available'?`${c.rolling12Months.from} → ${c.rolling12Months.to}`:'Janela ainda não disponível'} reference={c.latestReference} source="CAGED"/></div><p className="emp-callout">RAIS mostra vínculos existentes ao final do ano; Novo CAGED mostra movimentações mensais. Vínculos e movimentações não são pessoas únicas. Saldo não é estoque.</p></section>
 <Section id="emp-monthly" title="Movimentação do emprego formal" description={`Novo CAGED · ${period(c.latestReference)} · movimentações ajustadas até ${period(c.adjustedThrough)}.`}>{c.status==='available'&&last?<><div className="emp-latest"><div><span>Admissões</span><strong>{integer(last.admissions)}</strong></div><div><span>Desligamentos</span><strong>{integer(last.dismissals)}</strong></div><div><span>Saldo de vínculos</span><strong>{signed(last.balance)}</strong></div></div><p className="emp-narrative">{text.monthly}</p><h3>Evolução mensal · admissões, desligamentos e saldo</h3><MonthlyChart rows={c.monthly}/><h3>Saldo de empregos por mês</h3><p className="emp-muted">Positivo acima de zero, negativo abaixo de zero. O sinal aparece também na tabela e no valor ao selecionar o mês.</p><MonthlyChart rows={c.monthly} balanceOnly/><MonthlyTable rows={c.monthly}/><SourceNote source={cagedSource} reference={c.latestReference}/></>:<p className="notice">{c.reason??'Movimentação mensal não disponível.'}</p>}</Section>
 <Section id="emp-year" title={`Emprego no ano · ${c.latestReference?.slice(0,4)??'sem referência'}`} description="Acumulado desde janeiro até a última competência. Não equivale a um ano completo quando dezembro ainda não foi publicado."><p className="emp-narrative">{text.year}</p>{c.yearToDate?.status==='available'&&<div className="emp-latest"><div><span>Admissões no período</span><strong>{integer(c.yearToDate.admissions)}</strong></div><div><span>Desligamentos no período</span><strong>{integer(c.yearToDate.dismissals)}</strong></div><div><span>Saldo no período</span><strong>{signed(c.yearToDate.balance)}</strong></div></div>}<p className="emp-muted">Últimos 12 meses: {c.rolling12Months?.status==='available'?`${c.rolling12Months.from} → ${c.rolling12Months.to}, saldo de ${signed(c.rolling12Months.balance)} vínculos.`:'indisponível; é preciso ter as 12 competências completas.'}</p><SourceNote source={cagedSource} reference={c.latestReference}/></Section>
 <Section id="emp-sectors" title="Quais setores estão contratando?" description={`Novo CAGED · ${period(c.latestReference)} · grandes grupos oficiais de atividades.`}>{c.sectors?<><label className="emp-order">Ordenar setores por <select value={order} onChange={e=>setOrder(e.target.value as typeof order)}><option value="balance">Saldo (maior para menor)</option><option value="admissions">Admissões (maior para menor)</option></select></label><CategoryTable rows={[...c.sectors].sort((a,b)=>b[order]-a[order])} caption={`Movimentação por setor · ${c.latestReference} · ordenada por ${order==='balance'?'saldo':'admissões'}`}/><h3>Principais atividades · CNAE</h3><p className="emp-muted">Até 10 atividades detalhadas por admissões; categorias agregadas ao final. Proteção de pequenas células aplicada. CNAE descreve a atividade econômica.</p>{c.activities?.length?<CategoryTable rows={c.activities} limit={10} caption={`CNAE · ${c.latestReference} · maiores admissões`}/>:<p>Detalhamento indisponível ou suprimido para proteger pequenas células.</p>}<SourceNote source={cagedSource} reference={c.latestReference}/></>:<p>Movimentação setorial ainda não disponível.</p>}</Section>
 <Section id="emp-rais" title="Onde estão os empregos de Turvo?" description={`RAIS ${r.reference??'indisponível'} · vínculos formais ativos em 31 de dezembro.`}>{r.status==='available'&&r.sectors&&r.series?<><p className="emp-narrative">{text.rais} {text.sector}</p><StockChart sectors={r.sectors}/><div className="table-wrap"><table><caption>Estrutura RAIS {r.reference} · quantidade e participação no total de vínculos</caption><thead><tr><th>Atividade</th><th>Vínculos</th><th>Participação</th></tr></thead><tbody>{r.sectors.map(s=><tr key={s.code}><th scope="row">{s.label}</th><td>{integer(s.stock)}</td><td>{s.share.toLocaleString('pt-BR')}%</td></tr>)}</tbody></table></div><h3>Evolução anual · {r.series[0].period} → {r.reference}</h3><StockChart rows={r.series}/><details className="emp-table"><summary>Ver estoque e evolução setorial em tabela acessível</summary><div className="table-wrap"><table><caption>RAIS · vínculos ativos em 31/12 de cada ano</caption><thead><tr><th>Ano</th><th>Total</th>{r.sectors.map(s=><th key={s.code}>{s.label}</th>)}</tr></thead><tbody>{r.series.map(p=><tr key={p.period}><th scope="row">{p.period}</th><td>{integer(p.stock)}</td>{p.sectors.map(s=><td key={s.code}>{integer(s.stock)}</td>)}</tr>)}</tbody></table></div></details><p className="emp-muted">Cobertura da RAIS inclui vínculos celetistas e estatutários. Todos os grupos passaram à captação eSocial a partir de 2023; a série começa nesse ano e não interpola lacunas. Alterações na declaração podem afetar a comparação.</p><h3>Estabelecimentos</h3><p>{r.establishments?.reason??'Integração específica da RAIS Estabelecimento ainda não disponível.'}</p><SourceNote source={raisSource} reference={r.reference}/></>:<p className="notice">{r.reason??'Estoque anual ainda não disponível.'}</p>}</Section>
 <Section id="emp-occupations" title="Ocupações que mais contrataram" description={`CBO · Novo CAGED · ${period(c.latestReference)} · até 10 ocupações detalhadas por admissões; categorias agregadas ao final.`}>{c.occupations?.length?<CategoryTable rows={c.occupations} limit={10} caption={`Ocupações por admissões · ${c.latestReference} · categorias protegidas`}/>:<p>Detalhamento indisponível ou suprimido para proteger pequenas células.</p>}<p className="emp-muted">CBO identifica a ocupação; CNAE identifica a atividade do estabelecimento. “Outras categorias” reúne pequenas células. O arquivo CSV traz todas as categorias publicáveis, sem cruzamentos individuais.</p><SourceNote source={cagedSource} reference={c.latestReference}/></Section>
 <Section id="emp-salary" title="Remuneração e salários de admissão" description="Valores nominais em reais. Remuneração dos vínculos e salário das novas admissões são indicadores distintos."><h3>Salário médio das admissões · {period(c.latestReference)}</h3><p className="emp-salary-value">{money(last?.admissionSalary)}</p><p>{c.salaryMethod??'Salários ainda sem coleta validada.'}</p>{c.status==='available'&&<><MonthlyChart rows={c.monthly} salary/><MonthlyTable rows={c.monthly}/></>}<SourceNote source={cagedSource} reference={c.latestReference}/><h3>Remuneração média de dezembro · RAIS {r.reference}</h3>{r.remuneration?.status==='available'?<><p className="emp-salary-value">{money(r.remuneration.value)}</p><p>{r.remuneration.unit} · {integer(r.remuneration.sample)} vínculos com valor válido. Não é renda média da população.</p><p className="emp-muted">{integer(r.remuneration.missingOrZero)} vínculos ativos sem remuneração positiva de dezembro foram excluídos desta média, sem imputação. Coleta dos microdados: {date(r.remuneration.collectedAt??r.collectedAt)}. O valor é calculado pelo observatório a partir do campo nominal oficial.</p><div className="table-wrap"><table><caption>Remuneração nominal por setor · RAIS {r.reference} · média em R$</caption><thead><tr><th>Setor</th><th>Remuneração média</th><th>Amostra</th></tr></thead><tbody>{r.remuneration.sectors?.map(s=><tr key={s.label}><th scope="row">{s.label}</th><td>{money(s.value)}</td><td>{integer(s.sample)}</td></tr>)}</tbody></table></div></>:<p>{r.remuneration?.reason??'Remuneração RAIS ainda não disponível.'}</p>}<SourceNote source={raisSource} reference={r.reference}/></Section>
 <Comparison data={data}/><Methodology data={data}/></div>;
}
