import {ResponsiveContainer,ComposedChart,Bar,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend,BarChart,Cell,ReferenceLine,LineChart} from 'recharts';
import type {Month,StockSector,RaisYear} from './types';
import {integer,signed,money} from './data';
const grid=<CartesianGrid stroke="#e3ebe5" vertical={false}/>;
export function MonthlyChart({rows,balanceOnly=false,salary=false}:{rows:Month[];balanceOnly?:boolean;salary?:boolean}){
 const title=salary?'Salário médio das admissões (R$ nominais)':balanceOnly?'Saldo mensal de vínculos':'Admissões, desligamentos e saldo de vínculos';
 return <div className="emp-chart" role="img" aria-label={`${title} · ${rows[0].period} a ${rows.at(-1)!.period}. Valores na tabela acessível desta seção.`}><ResponsiveContainer width="100%" height="100%">{salary?<LineChart data={rows}>{grid}<XAxis dataKey="period" minTickGap={35}/><YAxis width={80} tickFormatter={integer}/><Tooltip formatter={v=>money(Number(v))}/><Line dataKey="admissionSalary" name="Salário das admissões" stroke="#236246" strokeWidth={2.5} connectNulls={false} isAnimationActive={false}/></LineChart>:balanceOnly?<BarChart data={rows}>{grid}<XAxis dataKey="period" minTickGap={35}/><YAxis tickFormatter={signed}/><ReferenceLine y={0} stroke="#283f31"/><Tooltip formatter={v=>signed(Number(v))}/><Bar dataKey="balance" name="Saldo" isAnimationActive={false}>{rows.map(r=><Cell key={r.period} fill={r.balance<0?'#a26232':'#287153'}/>)}</Bar></BarChart>:<ComposedChart data={rows}>{grid}<XAxis dataKey="period" minTickGap={35}/><YAxis tickFormatter={integer}/><ReferenceLine y={0} stroke="#283f31"/><Tooltip formatter={(v,name)=>name==='Saldo'?signed(Number(v)):integer(Number(v))}/><Legend wrapperStyle={{fontSize:12}}/><Bar dataKey="admissions" name="Admissões" fill="#2a7658" isAnimationActive={false}/><Bar dataKey="dismissals" name="Desligamentos" fill="#a9bcb0" isAnimationActive={false}/><Line dataKey="balance" name="Saldo" stroke="#a6712f" strokeWidth={2.5} dot={{r:3}} isAnimationActive={false}/></ComposedChart>}</ResponsiveContainer></div>;
}
export function StockChart({rows,sectors}:{rows?:RaisYear[];sectors?:StockSector[]}){
 return <div className="emp-chart" role="img" aria-label={`${sectors?'Vínculos formais por setor':'Estoque anual RAIS'} · quantidade de vínculos. Tabela acessível nesta seção.`}><ResponsiveContainer width="100%" height="100%">{sectors?<BarChart data={sectors} layout="vertical" margin={{left:0,right:20}}><CartesianGrid stroke="#e3ebe5" horizontal={false}/><XAxis type="number" tickFormatter={integer}/><YAxis type="category" dataKey="label" width={110} tick={{fontSize:12}}/><Tooltip formatter={v=>integer(Number(v))}/><Bar dataKey="stock" name="Vínculos em 31/12" fill="#2a7658" radius={[0,4,4,0]} isAnimationActive={false}/></BarChart>:<LineChart data={rows}>{grid}<XAxis dataKey="period"/><YAxis domain={[0,'auto']} tickFormatter={integer}/><Tooltip formatter={v=>integer(Number(v))}/><Line dataKey="stock" name="Vínculos em 31/12" stroke="#2a7658" strokeWidth={3} dot={{r:5}} isAnimationActive={false}/></LineChart>}</ResponsiveContainer></div>;
}
