import {ResponsiveContainer,AreaChart,Area,LineChart,Line,BarChart,Bar,CartesianGrid,XAxis,YAxis,Tooltip,Legend,Cell} from 'recharts';
import type {EconomyPoint,Composition,Sector} from './types';
import {currency,compactCurrency,percent} from './data';
export const COLORS=['#367859','#ae7b2d','#416c9b','#765b87'];
const grid=<CartesianGrid stroke="#e5ece7" vertical={false}/>;
const tipStyle={border:'1px solid #dce6df',borderRadius:8,fontSize:12};
export function GdpHistoryChart({rows,variation=false,perCapita=false}:{rows:EconomyPoint[];variation?:boolean;perCapita?:boolean}) {
 return <div className="eco-chart" role="img" aria-label={`${variation?'Variação nominal do PIB (%)':perCapita?'PIB per capita (R$ por habitante)':'PIB a preços correntes (R$)'} · ${rows[0].period}–${rows.at(-1)!.period}. Valores na tabela abaixo.`}><ResponsiveContainer width="100%" height="100%">
 {variation?<LineChart data={rows} margin={{left:5,right:20,top:15,bottom:8}}>{grid}<XAxis dataKey="period" tick={{fontSize:11}} minTickGap={25}/><YAxis tickFormatter={percent} width={65} tick={{fontSize:11}}/><Tooltip formatter={v=>v==null?'—':percent(Number(v))} labelFormatter={label=>`Ano ${label}`} contentStyle={tipStyle}/><Line dataKey="nominalChange" name="Variação nominal" stroke="#a67428" strokeWidth={2.5} dot={{r:3}} connectNulls={false} isAnimationActive={false}/></LineChart>:<AreaChart data={rows} margin={{left:5,right:20,top:15,bottom:8}}>{grid}<XAxis dataKey="period" tick={{fontSize:11}} minTickGap={25}/><YAxis tickFormatter={v=>perCapita?`${Number(v)/1000} mil`:compactCurrency(Number(v))} width={90} tick={{fontSize:11}}/><Tooltip formatter={v=>currency(Number(v))} labelFormatter={label=>`Ano ${label}`} contentStyle={tipStyle}/><Area type="linear" dataKey="value" name={perCapita?'PIB per capita':'PIB nominal'} stroke="#287252" fill="#d9ebdf" strokeWidth={2.5} isAnimationActive={false}/></AreaChart>}
 </ResponsiveContainer></div>;
}
export function SectorCompositionChart({sectors,period}:{sectors:Sector[];period:string}) {
 const rows=sectors.map(s=>({...s,short:s.id==='services'?'Serviços¹':s.id==='publicAdministration'?'Administração pública²':s.label}));
 return <div className="eco-sector-chart" role="img" aria-label={`Participação no VAB de Turvo · ${period} · %. Valores e nomes completos na tabela abaixo.`}><ResponsiveContainer width="100%" height="100%"><BarChart data={rows} layout="vertical" margin={{left:5,right:30,top:5,bottom:5}}><CartesianGrid stroke="#e5ece7" horizontal={false}/><XAxis type="number" domain={[0,100]} tickFormatter={percent} tick={{fontSize:10}}/><YAxis type="category" dataKey="short" width={145} tick={{fontSize:11}}/><Tooltip formatter={v=>percent(Number(v))} contentStyle={tipStyle}/><Bar dataKey="share" name="% do VAB" radius={[0,4,4,0]} barSize={22} isAnimationActive={false}>{rows.map((r,i)=><Cell key={r.id} fill={COLORS[i]}/>)}</Bar></BarChart></ResponsiveContainer></div>;
}
export function SectorHistoryChart({rows}:{rows:Composition[]}) {
 const points=rows.map(r=>Object.fromEntries([['period',r.period],...r.sectors.map(s=>[s.id,s.share])]));
 return <div className="eco-chart" role="img" aria-label={`Estrutura econômica de Turvo · ${rows[0].period}–${rows.at(-1)!.period} · participação no VAB (%). Tabela abaixo.`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={points} margin={{left:0,right:15,top:10,bottom:5}}>{grid}<XAxis dataKey="period" tick={{fontSize:11}} minTickGap={25}/><YAxis domain={[0,100]} tickFormatter={percent} tick={{fontSize:11}} width={55}/><Tooltip formatter={v=>percent(Number(v))} contentStyle={tipStyle}/><Legend wrapperStyle={{fontSize:11}}/>{rows[0].sectors.map((s,i)=><Area key={s.id} type="linear" dataKey={s.id} name={s.id==='services'?'Serviços¹':s.id==='publicAdministration'?'Administração pública²':s.label} stackId="sectors" stroke={COLORS[i]} fill={COLORS[i]} fillOpacity={.8} isAnimationActive={false}/>)}</AreaChart></ResponsiveContainer></div>;
}
export function CapitaComparisonChart({rows,period}:{rows:{name:string;value:number}[];period:string}) {
 return <div className="eco-chart" role="img" aria-label={`PIB per capita comparado · ${period} · R$ por habitante. Tabela abaixo.`}><ResponsiveContainer width="100%" height="100%"><BarChart data={rows} margin={{left:0,right:15,top:10,bottom:5}}>{grid}<XAxis dataKey="name" tick={{fontSize:11}}/><YAxis width={65} tickFormatter={v=>`${Number(v)/1000} mil`} tick={{fontSize:11}}/><Tooltip formatter={v=>currency(Number(v))} contentStyle={tipStyle}/><Bar dataKey="value" name="PIB per capita" radius={[5,5,0,0]} barSize={50} isAnimationActive={false}>{rows.map(r=><Cell key={r.name} fill={r.name==='Turvo'?'#267454':'#8fa99a'}/>)}</Bar></BarChart></ResponsiveContainer></div>;
}
