import {useEffect,useState} from 'react';
import {ChartNoAxesCombined} from 'lucide-react';
import type {EconomyData} from './types';
import {loadEconomy,narratives,currency,compactCurrency,percent,collectedDate} from './data';
import {Summary,Section,SourceNote,DownloadLink,HistoryTable,EconomyComparison,Methodology} from './EconomyComponents';
import {GdpHistoryChart,SectorCompositionChart,SectorHistoryChart} from './EconomyCharts';
import './economy.css';
export default function EconomyPage({comparisonOnly=false}:{comparisonOnly?:boolean}) {
 const [data,setData]=useState<EconomyData>(),[error,setError]=useState(''),[retry,setRetry]=useState(0),[variation,setVariation]=useState(false);
 useEffect(()=>{const controller=new AbortController();setError('');setData(undefined);loadEconomy(controller.signal).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[retry]);
 if(error)return <section className="panel" role="alert"><h2>Economia indisponível</h2><p>{error}</p><button onClick={()=>setRetry(n=>n+1)}>Tentar novamente</button></section>;
 if(!data)return <div role="status" className="loading">Carregando o retrato econômico…<div className="skeleton"/></div>;
 const structure=data.sectorComposition.series.at(-1)!,tax=data.taxes.latest,text=narratives(data);
 const source=(id:string)=>data.sources.find(s=>s.id===id)!;
 const warning=data.collection.failures.length>0&&<div className="notice" role="status">A última coleta falhou. Exibimos os dados validados em {collectedDate(data.collection.lastSuccessAt)}.<details><summary>Relatório da tentativa · {collectedDate(data.collection.attemptedAt)}</summary>{data.collection.failures.map(f=><p key={f}>{f}</p>)}</details></div>;
 if(comparisonOnly)return <div className="economy-page">{warning}<EconomyComparison data={data}/></div>;
 return <div className="economy-page">
  <div className="eco-intro"><div><span className="eyebrow"><ChartNoAxesCombined size={14}/> ECONOMIA EM NÚMEROS</span><h2>A produção do território.<br/>A estrutura da economia.</h2><p>PIB municipal, atividades econômicas e comparação regional, com os anos e conceitos de cada fonte.</p></div><DownloadLink path="economy.json">Baixar dados de Economia</DownloadLink></div>
  <nav className="eco-jump" aria-label="Seções de Economia">{[['eco-summary','Panorama'],['eco-history','PIB histórico'],['eco-capita','Por habitante'],['eco-sectors','Atividades'],['eco-structure','Estrutura no tempo'],['eco-comparison','Comparação'],['eco-sources','Fontes']].map(([id,label])=><button key={id} onClick={()=>document.getElementById(id)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}>{label}</button>)}</nav>
  {warning}
  <section id="eco-summary"><div className="section-title"><h2>Economia em números</h2><span>PIB: {data.gdp.latest.period} · Estrutura: {structure.period}</span></div><Summary data={data}/><p className="eco-callout">O PIB municipal possui resultado mais recente que a abertura por atividade econômica. Os cards mantêm suas próprias referências.</p></section>
  <Section id="eco-history" number="01" title="Evolução do PIB" description={`Produto Interno Bruto de Turvo · ${data.gdp.series[0].period}–${data.gdp.latest.period} · valores a preços correntes em R$.`}>
   <div className="eco-history-layout"><div><div className="eco-toggle" role="group" aria-label="Medida do gráfico de PIB"><button aria-pressed={!variation} onClick={()=>setVariation(false)}>Valor do PIB</button><button aria-pressed={variation} onClick={()=>setVariation(true)}>Variação nominal</button></div><GdpHistoryChart rows={data.gdp.series} variation={variation}/><HistoryTable rows={data.gdp.series}/></div><aside className="eco-highlight"><span className="eyebrow">{data.gdp.latest.from} → {data.gdp.latest.period}</span><strong>{data.gdp.latest.nominalChange==null?'—':percent(data.gdp.latest.nominalChange)}</strong><h3>Variação nominal do PIB</h3><p>{text.change}</p></aside></div>
   <p className="eco-narrative">{text.gdp}</p><p className="eco-muted">Sem correção pela inflação e sem interpolação de anos. Variação = (PIB atual / PIB anterior − 1) × 100; quando houver intervalo maior que um ano, a tabela identifica os períodos, sem chamar de taxa anual.</p><SourceNote source={source(data.gdp.sourceId)}/>
  </Section>
  <Section id="eco-capita" number="02" title="PIB por habitante" description={`PIB per capita oficial · ${data.gdpPerCapita.series[0].period}–${data.gdpPerCapita.latest.period} · R$ por habitante, a preços correntes.`}>
   <p className="eco-narrative">{text.capita}</p><p className="eco-callout">PIB per capita divide a produção econômica municipal pela população utilizada na metodologia oficial. Não representa renda média das pessoas nem salário. Utilizamos o valor publicado pelo IBGE, sem recalcular com o Censo ou estimativas de outro módulo.</p><GdpHistoryChart rows={data.gdpPerCapita.series} perCapita/><HistoryTable rows={data.gdpPerCapita.series} capita/><SourceNote source={source(data.gdpPerCapita.sourceId)}/>
  </Section>
  <Section id="eco-sectors" number="03" title={`De onde vem a economia · ${structure.period}`} description={`Último detalhamento disponível · ${structure.period}. Participações oficiais no Valor Adicionado Bruto (VAB), antes dos impostos sobre produtos.`}>
   <p className="eco-narrative">{text.sector}</p><div className="eco-callout">Em 2022 e 2023, o IBGE publicou PIB e PIB per capita sem a tradicional abertura setorial. Esta estrutura é de {structure.period}, não do PIB {data.gdp.latest.period}. <a href={data.methodology.officialUrl} target="_blank" rel="noreferrer">Entenda a publicação ↗</a></div>
   <h3>Estrutura econômica de Turvo — {structure.period}</h3><p className="eco-muted">Participação no VAB (%) · valores absolutos em R$</p><SectorCompositionChart sectors={structure.sectors} period={structure.period}/>
   <div className="table-wrap"><table><caption>Atividades econômicas · {structure.period} · denominador dos percentuais: VAB total</caption><thead><tr><th scope="col">Atividade</th><th scope="col">VAB (R$)</th><th scope="col">% do VAB</th><th scope="col">Variáveis: valor / %</th></tr></thead><tbody>{structure.sectors.map(s=><tr key={s.id}><th scope="row">{s.label}</th><td>{currency(s.value)}</td><td>{percent(s.share)}</td><td>{s.variableId} / {s.shareVariableId}</td></tr>)}<tr><th scope="row">VAB total</th><td>{currency(structure.vabTotal)}</td><td>100%</td><td>498</td></tr></tbody></table></div>
   <p className="eco-muted">¹ Serviços excluem administração pública. ² Administração pública inclui defesa, educação e saúde públicas e seguridade social. Percentuais publicados com duas casas podem somar aproximadamente 100% por arredondamento.</p>
   <aside className="eco-tax"><div><span className="eyebrow">IMPOSTOS LÍQUIDOS DE SUBSÍDIOS · {tax.period}</span><h3>{compactCurrency(tax.value)}</h3><p>{currency(tax.value)} · {percent(tax.shareOfGdp!)} do PIB do mesmo ano (cálculo derivado).</p></div><p>Impostos sobre produtos são separados das atividades econômicas. Sua participação usa o PIB, enquanto a dos setores usa o VAB. Não somamos esses percentuais.</p></aside>
   <p className="eco-muted">Consistência contábil em {structure.period}: PIB {currency(data.gdp.series.find(p=>p.period===structure.period)!.value)} ≈ VAB {currency(structure.vabTotal)} + impostos {currency(data.taxes.series.find(p=>p.period===structure.period)!.value)}. Valores oficiais preservados, com tolerância de arredondamento.</p>
   <details className="eco-table"><summary>Histórico dos impostos líquidos de subsídios</summary><div className="table-wrap"><table><caption>Impostos sobre produtos · R$ e percentual derivado do PIB do mesmo ano</caption><thead><tr><th>Ano</th><th>Impostos (R$)</th><th>% do PIB</th></tr></thead><tbody>{data.taxes.series.map(p=><tr key={p.period}><th scope="row">{p.period}</th><td>{currency(p.value)}</td><td>{percent(p.shareOfGdp!)}</td></tr>)}</tbody></table></div></details><SourceNote source={source(data.sectorComposition.sourceId)} period={`${structure.period} · última abertura; série ${data.sectorComposition.series[0].period}–${structure.period}`}/>
  </Section>
  <Section id="eco-structure" number="04" title="Como a estrutura mudou" description={`Estrutura econômica de Turvo · ${data.sectorComposition.series[0].period}–${structure.period} · participação no VAB (%), somente anos com abertura oficial.`}>
   <SectorHistoryChart rows={data.sectorComposition.series}/><details className="eco-table"><summary>Ver participação setorial e VAB total por ano</summary><div className="table-wrap"><table><caption>Percentuais oficiais do VAB total · referência de cada linha</caption><thead><tr><th scope="col">Ano</th><th scope="col">VAB total (R$)</th><th scope="col">Agropecuária (%)</th><th scope="col">Indústria (%)</th><th scope="col">Serviços¹ (%)</th><th scope="col">Administração pública² (%)</th></tr></thead><tbody>{data.sectorComposition.series.map(p=><tr key={p.period}><th scope="row">{p.period}</th><td>{currency(p.vabTotal)}</td>{p.sectors.map(s=><td key={s.id}>{percent(s.share)}</td>)}</tr>)}</tbody></table></div></details><p className="eco-muted">¹ Serviços, exceto administração, defesa, educação e saúde públicas e seguridade social. ² Esse conjunto de atividades públicas aparece separadamente. Percentuais oficiais preservados, sem normalização artificial para 100%.</p><SourceNote source={source(data.sectorComposition.sourceId)} period={`${data.sectorComposition.series[0].period}–${structure.period}`}/>
  </Section>
  <EconomyComparison data={data}/><Methodology data={data}/>
 </div>;
}
