import type {ReactNode} from 'react';
import {Download,ExternalLink} from 'lucide-react';
import type {EconomyData,EconomySource,EconomyPoint} from './types';
import {currency,compactCurrency,percent,collectedDate,economyUrl,comparisonRows} from './data';
import {CapitaComparisonChart} from './EconomyCharts';
export function Section({id,number,title,description,children}:{id:string;number:string;title:string;description:string;children:ReactNode}) {
 return <section className="panel eco-section" id={id}><header><span className="eyebrow">{number} / ECONOMIA MUNICIPAL</span><h2>{title}</h2><p>{description}</p></header>{children}</section>;
}
export function DownloadLink({path,children}:{path:string;children:ReactNode}) {return <a className="eco-download" href={economyUrl(path)} download><Download size={15}/>{children}</a>;}
export function SourceNote({source,period}:{source:EconomySource;period?:string}) {
 return <div className="eco-source"><a href={source.url} target="_blank" rel="noreferrer">IBGE · {source.table?`Tabela ${source.table}`:`Pesquisa 38 · Indicador ${source.indicator}`} <ExternalLink size={11}/></a><span>Referência: {period??`${source.periods[0]}–${source.periods.at(-1)}`} · Coleta: {collectedDate(source.collectedAt)}</span></div>;
}
export function Summary({data}:{data:EconomyData}) {
 const sources=Object.fromEntries(data.sources.map(s=>[s.id,s]));
 return <div className="cards eco-cards">{Object.values(data.summary).map(metric=>{
 const leading=metric.id==='economy-leading-sector';
 const value=metric.id==='gdp'?compactCurrency(metric.value):metric.id==='gdp-per-capita'?currency(metric.value):leading?metric.concept:percent(metric.value);
 return <article className={`indicator eco-metric ${leading?'eco-leading':''}`} key={metric.id}><div className="card-top"><span>{metric.title}</span><span className="badge real">IBGE</span></div><strong>{value}</strong><div className="unit">{leading?`${percent(metric.value)} do VAB`:metric.unit==='%'?'Variação nominal':metric.unit==='R$ por habitante'?'por habitante':'Preços correntes'} · <b>{metric.reference}</b></div><p>{leading?'Maior participação na última abertura setorial publicada.':metric.concept}</p><SourceNote source={sources[metric.sourceId]} period={metric.reference}/></article>;
 })}</div>;
}
export function HistoryTable({rows,capita=false}:{rows:EconomyPoint[];capita?:boolean}) {
 return <details className="eco-table"><summary>Ver {capita?'PIB per capita':'PIB e variação nominal'} em tabela acessível</summary><div className="table-wrap"><table><caption>{capita?'PIB per capita oficial · R$ por habitante':'PIB a preços correntes · R$ · variação nominal entre observações consecutivas'}</caption><thead><tr><th scope="col">Ano</th><th scope="col">{capita?'PIB per capita':'PIB'}</th>{!capita&&<><th scope="col">Variação nominal</th><th scope="col">Períodos comparados</th></>}</tr></thead><tbody>{rows.map(p=><tr key={p.period}><th scope="row">{p.period}</th><td>{currency(p.value)}</td>{!capita&&<><td>{p.nominalChange==null?'—':percent(p.nominalChange)}</td><td>{p.from?`${p.from} → ${p.period}${p.annual?'':' (intervalo entre observações)'}`:'Sem observação anterior'}</td></>}</tr>)}</tbody></table></div></details>;
}
export function EconomyComparison({data}:{data:EconomyData}) {
 const rows=comparisonRows(data);
 const capitaPeriod=data.gdpPerCapita.latest.period,structurePeriod=data.sectorComposition.latestPeriod;
 const chartRows=rows.filter(r=>r.capita!==null).map(r=>({name:r.name,value:r.capita!.value}));
 return <Section id="eco-comparison" number="05" title="Turvo em perspectiva" description={`PIB e variação nominal: ${data.gdp.latest.period}. PIB per capita: ${capitaPeriod}. Abertura setorial: ${structurePeriod}. Mesma metodologia, unidade e ano em cada comparação.`}>
  <p className="eco-callout">PIB total depende do tamanho da economia. PIB per capita não representa renda individual média da população, salário ou qualidade de vida.</p>
  <h3>PIB por habitante · {capitaPeriod}</h3><p className="eco-muted">R$ por habitante · série revisada oficial</p><CapitaComparisonChart rows={chartRows} period={capitaPeriod}/>
  <div className="table-wrap"><table><caption>Comparação municipal · unidades e referências identificadas</caption><thead><tr><th scope="col">Município</th><th scope="col">PIB (R$) · {data.gdp.latest.period}</th><th scope="col">PIB per capita (R$) · {capitaPeriod}</th><th scope="col">Variação nominal (%)<br/>{data.gdp.latest.from} → {data.gdp.latest.period}</th><th scope="col">Principal atividade · {structurePeriod}</th></tr></thead><tbody>{rows.map(r=><tr className={r.name==='Turvo'?'eco-own':''} key={r.code}><th scope="row">{r.name} / PR<br/><small>IBGE {r.code}</small></th><td>{r.gdp?currency(r.gdp.value):'—'}</td><td>{r.capita?currency(r.capita.value):'—'}</td><td>{r.change==null?'—':percent(r.change)}</td><td>{r.composition?`${r.composition.sectors.find(s=>s.id===r.composition!.leadingSector)!.label} (${percent(r.composition.sectors.find(s=>s.id===r.composition!.leadingSector)!.share)})`:'—'}</td></tr>)}</tbody></table></div>
  <details className="eco-table"><summary>Comparar participação por atividade · {structurePeriod}</summary><div className="table-wrap"><table><caption>Percentuais oficiais do VAB total · {structurePeriod}</caption><thead><tr><th scope="col">Município</th>{data.sectorComposition.series.at(-1)!.sectors.map(s=><th scope="col" key={s.id}>{s.id==='services'?'Serviços¹':s.id==='publicAdministration'?'Administração pública²':s.label} (%)</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.code}><th scope="row">{r.name}</th>{data.sectorComposition.series.at(-1)!.sectors.map(s=><td key={s.id}>{r.composition?percent(r.composition.sectors.find(p=>p.id===s.id)!.share):'—'}</td>)}</tr>)}</tbody></table></div></details>
  <p className="eco-muted">¹ Serviços excluem administração pública. ² Administração, defesa, educação e saúde públicas e seguridade social. — indica dado ausente ou referência, unidade ou método incompatível.</p>
  <details className="eco-table"><summary>Fontes por município e indicador</summary>{data.sources.map(s=><div key={s.id}><b>{[data,...data.comparisons].find(m=>m.municipality.code===s.municipalityCode)?.municipality.name}</b><SourceNote source={s}/></div>)}</details>
 </Section>;
}
export function Methodology({data}:{data:EconomyData}) {
 return <Section id="eco-sources" number="06" title="Fontes e metodologia" description="Dados oficiais do IBGE. Cada consulta mantém variáveis, unidades, períodos, município e resposta bruta para auditoria.">
 <div className="eco-definitions"><div><h3>O que mede o PIB?</h3><p>O Produto Interno Bruto mede o valor dos bens e serviços finais produzidos no território municipal.</p><h3>PIB por habitante</h3><p>É a relação entre o PIB e a população utilizada no cálculo oficial. Não representa salário ou renda média dos moradores; nem toda renda produzida no município é apropriada por sua população.</p></div><div><h3>Valores a preços correntes</h3><p>Os valores monetários refletem os preços de cada ano e não estão descontados da inflação. A variação nominal inclui mudanças de preços e de produção. Não publicamos uma série de PIB real municipal.</p><h3>Valor adicionado e impostos</h3><p>O VAB representa o valor gerado pelas atividades antes dos impostos líquidos de subsídios sobre produtos. PIB ≈ VAB total + esses impostos. Percentuais dos setores usam o VAB como denominador; os impostos ficam separados.</p></div></div>
 <p className="eco-callout">O componente de administração pública do VAB abrange administração, defesa, educação e saúde públicas e seguridade social. Ele não equivale à receita, despesa ou orçamento da Prefeitura de Turvo.</p>
 <p className="eco-muted">A publicação 2022/2023 trouxe somente PIB e PIB per capita, sem abertura do VAB, VAB total e impostos. <a href={data.methodology.officialUrl} target="_blank" rel="noreferrer">Publicação e conceitos oficiais</a> · <a href={data.methodology.sectorGapUrl} target="_blank" rel="noreferrer">Nota técnica do IBGE</a>. Atualização do dado: anual; verificação planejada: semanal. Revisões podem alterar anos anteriores.</p>
 <div className="table-wrap"><table><caption>Proveniência completa das consultas publicadas</caption><thead><tr><th>Município / órgão</th><th>Pesquisa / tabela / indicador</th><th>Períodos</th><th>Coleta</th><th>Auditoria</th></tr></thead><tbody>{data.sources.map(s=><tr key={s.id}><th scope="row">{s.municipalityCode}<br/>IBGE</th><td>{s.research}<br/>{s.table?`Tabela ${s.table}`:`Pesquisa 38 · Indicador ${s.indicator}`}</td><td>{s.periods[0]}–{s.periods.at(-1)}</td><td>{collectedDate(s.collectedAt)}</td><td><a href={s.url} target="_blank" rel="noreferrer">Consulta oficial</a><br/><a href={s.metadataUrl} target="_blank" rel="noreferrer">Metadados</a><br/><a href={economyUrl(s.rawPath)} download>Resposta bruta</a></td></tr>)}</tbody></table></div>
 <details className="eco-table"><summary>Dicionário de variáveis e transformações</summary>{data.sources.filter(s=>s.municipalityCode==='4127965').map(s=><div key={s.id}><h3>{s.title}</h3><p>{s.methodology}</p><div className="table-wrap"><table><caption>{s.table?`Variáveis da tabela ${s.table}`:'Indicador da API Pesquisas'}</caption><thead><tr><th>ID</th><th>Conceito</th><th>Unidade de origem</th></tr></thead><tbody>{s.variables.map(v=><tr key={v.id}><th scope="row">{v.id}</th><td>{v.name}</td><td>{v.unit}</td></tr>)}</tbody></table></div><p>Classificações/categorias: {s.classifications.length?'ver snapshot':'nenhuma dimensão classificatória nesta consulta; atividades são variáveis distintas'}.</p><ul>{s.transformations.map(t=><li key={t}>{t}</li>)}</ul>{s.hierarchyUrl&&<a href={s.hierarchyUrl} target="_blank" rel="noreferrer">Hierarquia oficial do conceito PIB per capita</a>}</div>)}</details>
 <div className="eco-downloads"><h3>Baixar dados de Economia</h3><p>JSON completo e CSVs dos quatro municípios, com unidades, códigos e fontes. Valores preservados na precisão publicada pelo IBGE.</p><div>{[['economy.json','Dataset completo · JSON'],['gdp.csv','PIB · CSV'],['gdp-per-capita.csv','PIB por habitante · CSV'],['economy-sectors.csv','Atividades econômicas · CSV']].map(([path,label])=><DownloadLink key={path} path={path}>{label}</DownloadLink>)}</div></div>
 </Section>;
}
