import {useState,type ReactNode} from 'react';
import {Download,ExternalLink,Hospital,MapPin} from 'lucide-react';
import {CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import type {HealthData,Group,Pending} from './types';
import {dataUrl,number,reference,typeShort} from './data';
export function Section({id,title,description,children}:{id:string;title:string;description?:string;children:ReactNode}){return <section id={id} className="panel health-section"><span className="eyebrow">SAÚDE · TURVO / PR</span><h2>{title}</h2>{description&&<p className="health-muted">{description}</p>}{children}</section>;}
export function SourceNote({data,id}:{data:HealthData;id:string}){const s=data.sources.find(s=>s.id===id);if(!s)return null;return <p className="source health-source"><a href={s.catalogUrl} target="_blank" rel="noreferrer">{s.source} <ExternalLink size={11}/></a><span>{id==='cnes'?'Exportação diária':id==='beds'?'Competência':'Divisão regional'}: {reference(s.reference)} · Coleta: {new Date(s.collectedAt).toLocaleDateString('pt-BR')}</span></p>;}
export function PendingBlock({item}:{item:Pending}){return <article className="health-pending"><span>AINDA NÃO INTEGRADO</span><h3>{item.title}</h3><p>{item.reason}</p><a href={item.url} target="_blank" rel="noreferrer">Consultar sistema oficial <ExternalLink size={12}/></a></article>;}
export function Distribution({groups,title,date}:{groups:Group[];title:string;date:string}){const max=Math.max(...groups.map(g=>g.count),1);return <article className="health-distribution"><h3>{title}</h3><p className="health-muted">{reference(date)} · estabelecimentos ativos</p><div aria-hidden="true" className="health-bars">{groups.map(g=><div key={g.label}><span>{g.label}</span><div><i style={{width:`${g.count/max*100}%`}}/><b>{number(g.count)}</b></div></div>)}</div><details><summary>Ver tabela acessível · {title.toLowerCase()}</summary><div className="table-wrap"><table><caption>{title} · {reference(date)} · estabelecimentos ativos</caption><thead><tr><th>Classificação</th><th>Quantidade</th></tr></thead><tbody>{groups.map(g=><tr key={g.label}><th scope="row">{g.label}</th><td>{g.count}</td></tr>)}</tbody></table></div></details></article>;}
export function BedHistory({data}:{data:HealthData}){const rows=data.beds.series.filter(r=>r.municipalityCode==='4127965').map(r=>({...r,period:reference(r.reference)}));return <><h3>Capacidade cadastrada ao longo de {data.beds.reference.slice(0,4)}</h3><p className="health-muted">Leitos · competências oficiais de {reference(rows[0]?.reference)} a {reference(data.beds.reference)}</p><div className="health-chart" aria-hidden="true"><ResponsiveContainer width="100%" height="100%"><LineChart data={rows} margin={{top:15,right:20,left:0,bottom:15}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="reference" tickFormatter={r=>`${r.slice(4)}/${r.slice(0,4)}`} tick={{fontSize:11}}/><YAxis allowDecimals={false} domain={[0,'auto']}/><Tooltip labelFormatter={r=>reference(String(r))}/><Line name="Leitos existentes" type="linear" dataKey="existing" stroke="#1d5748" strokeWidth={3} dot={{r:5}}/><Line name="Leitos SUS" type="linear" dataKey="sus" stroke="#c69642" strokeWidth={2} strokeDasharray="6 4" dot={{r:3}}/></LineChart></ResponsiveContainer></div><p className="health-muted">Linha contínua: existentes · tracejada: SUS. {rows.every(r=>r.existing===r.sus)?'As duas séries coincidem nesta publicação.':'Valores podem diferir por competência.'}</p><details><summary>Ver série de leitos em tabela acessível</summary><div className="table-wrap"><table><caption>Turvo · capacidade hospitalar cadastrada · leitos</caption><thead><tr><th>Competência</th><th>Existentes</th><th>SUS</th><th>UTI existentes</th><th>UTI SUS</th></tr></thead><tbody>{rows.map(r=><tr key={r.reference}><th scope="row">{r.period}</th><td>{r.existing}</td><td>{r.sus}</td><td>{r.icuExisting}</td><td>{r.icuSus}</td></tr>)}</tbody></table></div></details></>;}
export function Comparison({data}:{data:HealthData}){return <Section id="health-comparison" title="Turvo em perspectiva" description="Mesmos arquivos, critérios de cadastro e referências para os quatro municípios."><div className="table-wrap"><table><caption>Rede: exportação de {reference(data.network.reference)} · leitos: {reference(data.beds.reference)}</caption><thead><tr><th>Município</th><th>Estabelecimentos ativos</th><th>UBS</th><th>SUS ambulatorial</th><th>Leitos existentes</th><th>Leitos SUS</th></tr></thead><tbody>{data.comparison.map(r=><tr className={r.municipalityCode==='4127965'?'health-highlight':''} key={r.municipalityCode}><th scope="row">{r.name}<small>{r.municipalityCode} · PR</small></th><td>{number(r.network.active)}</td><td>{number(r.network.ubs)}</td><td>{number(r.network.sus.ambulatoryYes)}</td><td>{number(r.beds.existing)}</td><td>{number(r.beds.sus)}{r.beds.zeroConfirmed&&<small>Sem registros ativos no arquivo completo</small>}</td></tr>)}</tbody></table></div><p>Os totais absolutos dependem também do tamanho da população e do papel regional da rede. Não expressam cobertura, suficiência ou qualidade. Indicadores por habitante aguardam denominadores populacionais compatíveis com o período de cada base.</p><SourceNote data={data} id="cnes"/><SourceNote data={data} id="beds"/></Section>;}
export function NetworkMap({data}:{data:HealthData}){
 const [selected,setSelected]=useState('');const geometry=data.map.geometry;
 if(!geometry)return <p>Mapa ainda não disponível. Os endereços oficiais estão na tabela de unidades.</p>;
 const polygons=geometry.type==='Polygon'?[geometry.coordinates as number[][][]]:geometry.coordinates as number[][][][];
 const flat=polygons.flat(2),xs=flat.map(v=>v[0]),ys=flat.map(v=>v[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),scale=Math.min(560/((maxX-minX)*Math.cos(25*Math.PI/180)),360/(maxY-minY));
 const project=(p:number[])=>[(p[0]-(maxX+minX)/2)*Math.cos(25*Math.PI/180)*scale+300,((maxY+minY)/2-p[1])*scale+200];
 const path=polygons.map(rings=>rings.map(r=>r.map((p,i)=>`${i?'L':'M'}${project(p).join(',')}`).join(' ')+'Z').join(' ')).join(' ');
 const shown=data.network.establishments.filter(r=>r.mapEligible),sel=shown.find(r=>r.cnes===selected);
 return <div className="health-map-grid"><div><svg viewBox="0 0 600 400" className="health-map" role="group" aria-label="Mapa da rede de saúde de Turvo. Selecione um ponto ou use a lista ao lado."><path d={path} fill="#e6eee7" stroke="#a8bba9" fillRule="evenodd"/>{shown.map(r=>{const [x,y]=project([r.coordinates!.longitude,r.coordinates!.latitude]);const symbol=r.ubs?'U':r.hospital?'H':r.urgent?'!':'•';return <g key={r.cnes} role="button" tabIndex={0} aria-label={`${r.name}, ${typeShort[r.typeCode]??r.type}`} onClick={()=>setSelected(r.cnes)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(r.cnes);}}} transform={`translate(${x},${y})`}><title>{r.name}</title><circle r={selected===r.cnes?10:8} fill={r.ubs?'#1d5748':r.hospital?'#9b732f':r.urgent?'#8c4961':'#576d7e'} stroke="#fff" strokeWidth={2}/><text textAnchor="middle" y={3} fontSize={9} fill="#fff" pointerEvents="none">{symbol}</text></g>;})}</svg><p className="health-map-legend">U · UBS &nbsp; H · Hospital &nbsp; ! · Urgência &nbsp; • · Demais unidades</p></div><div><label className="health-map-select"><MapPin size={16}/> Localizar unidade<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecione uma unidade</option>{shown.map(r=><option key={r.cnes} value={r.cnes}>{r.name}</option>)}</select></label><div className="health-map-detail" aria-live="polite">{sel?<><h3>{sel.name}</h3><p>{sel.address}<br/>{sel.neighborhood??'Bairro não informado'}</p><p>{typeShort[sel.typeCode]??sel.type} · CNES {sel.cnes}</p><a href={sel.cnesUrl} target="_blank" rel="noreferrer">Ver no CNES <ExternalLink size={12}/></a></>:<><Hospital size={24}/><h3>A rede no território</h3><p>{data.map.shown} cadastros ativos com coordenadas dentro do limite municipal.</p></>}</div><p className="health-muted">{data.map.coordinateConcept} Limite municipal IBGE {data.map.geometryReference}. O catálogo permite localizar pontos sobrepostos.</p></div></div>;
}
export function Methodology({data}:{data:HealthData}){return <Section id="health-sources" title="Fontes e metodologia" description="Informação institucional pública, com origem, conceito e datas verificáveis."><div className="health-downloads">{[['health.json','Snapshot completo'],['exports/health-establishments.csv','Estabelecimentos · CSV'],['exports/health-beds.csv','Leitos · CSV'],['exports/health-primary-care.csv','UBS · CSV']].map(([file,label])=><a key={file} href={dataUrl(file)} download><Download size={14}/>{label}</a>)}</div>{data.sources.map(s=><details className="health-source-detail" key={s.id}><summary>{s.dataset} · {reference(s.reference)}</summary><p>{s.concept}</p><dl>{Object.entries({'Órgão':s.agency,'Referência':reference(s.reference),'Competência':s.competence?reference(s.competence):'Não informada na exportação diária','Publicação do recurso':s.publishedAt,'Coleta':s.collectedAt,'Território':'Turvo/PR · IBGE 4127965 (412796 no DATASUS)','Transformação':s.transformation,'Tamanho do ZIP':`${number(s.bytes)} bytes`,'SHA-256':s.sha256}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><a href={s.catalogUrl} target="_blank" rel="noreferrer">Catálogo oficial</a> · <a href={s.url} target="_blank" rel="noreferrer">Arquivo original nacional</a>{s.typeClassificationUrl&&<> · <a href={s.typeClassificationUrl} target="_blank" rel="noreferrer">Classificação oficial CNES</a></>}</details>)}<div className="health-two"><article><h3>Estrutura, atendimento e tempo</h3><p>“Ativo” significa ausência de motivo de desativação no cadastro. Incluímos unidades assistenciais e administrativas registradas, diferenciadas por tipo. Não é confirmação de atendimento em tempo real.</p><p>O cadastro atual não contém competência mensal. Sua referência é a data oficial de publicação da exportação. A série de leitos usa competências mensais próprias; não reconstruímos a história da rede a partir do cadastro atual.</p></article><article><h3>Atendimento SUS e privacidade</h3><p>{data.network.susDefinition}</p><p>Publicamos somente estabelecimentos e agregados. Nenhum nome de paciente ou profissional, CPF, CNS, prontuário ou contato individual integra o snapshot. Indicadores clínicos futuros dependem de agregação segura e política de divulgação documentada.</p></article></div><p>Atualização mensal preparada, sem consultas às fontes pelo navegador. Falhas preservam o último snapshot validado. MCP Brasil foi utilizado como referência técnica; a fonte dos indicadores é o Ministério da Saúde / DATASUS / CNES.</p></Section>;}
