import type {EducationData,EducationMetric} from './types';
export const labels:Record<string,string>={total:'Educação básica',infant:'Educação infantil',nursery:'Creche',preschool:'Pré-escola',fundamental:'Ensino fundamental',initial:'Anos iniciais',final:'Anos finais',secondary:'Ensino médio',professional:'Educação profissional',eja:'EJA',special:'Educação especial',fullTime:'Tempo integral'};
export const metricLabels:Record<string,string>={ideb:'IDEB',literacy:'Crianças alfabetizadas',literacyTarget:'Meta oficial',literacyParticipation:'Participação na avaliação',dsu:'Docentes com curso superior',tdi:'Distorção idade-série',atu:'Média de alunos por turma',had:'Média de horas-aula diárias',flowApproval:'Aprovação',flowRepetition:'Reprovação',flowDropout:'Abandono'};
export const format=(v:number|null|undefined,unit='')=>v==null?'Não divulgado':`${v.toLocaleString('pt-BR',{maximumFractionDigits:2})}${unit==='%'?'%':unit?' '+unit:''}`;
export const dataUrl=(file:string)=>`${import.meta.env.BASE_URL}data/${file}`;
export function validate(data:EducationData):EducationData {
 if(data?.schemaVersion!==1||data?.municipality?.code!=='4127965'||data?.municipality?.state!=='PR'||!Array.isArray(data.census?.series)||!Array.isArray(data.indicators)||!Array.isArray(data.sources)||!Array.isArray(data.schools)||!Array.isArray(data.infrastructure)||!Array.isArray(data.collection?.failures))throw Error('Arquivo de Educação incompatível com Turvo/PR.');
 const ids=new Set(data.sources.map(s=>s.id));if(ids.size!==data.sources.length||data.sources.some(s=>s.agency!=='INEP'||!s.url.startsWith('https://download.inep.gov.br/')||!/^\d{4}$/.test(s.reference)))throw Error('Fonte educacional inválida.');
 for(const r of data.indicators){if(!ids.has(r.sourceId)||r.state!=='PR'||!['4127965','4109401','4119608','4113254','41'].includes(r.code)||r.value!==null&&(!Number.isFinite(r.value)||r.value<0||r.unit==='%'&&r.value>100||r.unit==='IDEB'&&r.value>10))throw Error('Indicador educacional inválido.');}
 for(const r of data.census.series){if(r.state!=='PR'||!ids.has(r.sourceId)||Object.values(r.enrolments).some(v=>v!==null&&(!Number.isInteger(v)||v<0)))throw Error('Matrículas ou fonte inválidas.');}
 for(const s of data.schools){if(!/^\d{8}$/.test(s.code)||!['4127965','4109401','4119608','4113254'].includes(s.municipalityCode))throw Error('Escola de território inválido.');}
 for(const r of data.infrastructure){if(![r.considered,r.withResource,r.missing,r.activeSchools].every(v=>Number.isInteger(v)&&v>=0)||r.withResource>r.considered||r.considered+r.missing!==r.activeSchools||r.percent!== (r.considered?Math.round(r.withResource/r.considered*10000)/100:null))throw Error('Denominador de infraestrutura inválido.');}
 return data;
}
export async function loadEducation(signal?:AbortSignal){const response=await fetch(dataUrl('education.json'),{signal});if(!response.ok)throw Error('Não foi possível carregar os dados de Educação.');return validate(await response.json());}
export function latest(rows:EducationMetric[],kind:string,stage?:string){return rows.filter(r=>r.metric===kind&&(!stage||r.stage===stage)).sort((a,b)=>b.reference.localeCompare(a.reference))[0];}
export function narrative(value:number|null|undefined,year:string|null,network:string){return value==null?'Matrículas ainda não disponíveis.':`Em ${year}, ${network==='Total'?'todas as redes de Turvo':`a rede ${network.toLowerCase()} de Turvo`} ${network==='Total'?'registraram':'registrou'} ${format(value)} matrículas na educação básica. Matrículas não representam estudantes únicos.`;}
