import type {ReactNode} from 'react';
import type {EducationData,EducationMetric} from './types';
import {format,metricLabels,latest,dataUrl} from './data';
export function Section({id,title,description,children}:{id:string;title:string;description?:string;children:ReactNode}){return <section className="panel edu-section" id={id}><span className="eyebrow">EDUCAÇÃO BÁSICA · TURVO / PR</span><h2>{title}</h2>{description&&<p className="edu-muted">{description}</p>}{children}</section>;}
export function SourceNote({data,keys}:{data:EducationData;keys:string[]}){return <p className="source">Fonte: INEP · {keys.map(key=>{const sources=data.sources.filter(s=>s.key===key).sort((a,b)=>b.reference.localeCompare(a.reference)),s=sources[0];return s?<span key={key}><a href={s.officialUrl} target="_blank" rel="noreferrer">{key==='census'?'Censo Escolar':s.label||key}</a> · {sources.at(-1)?.reference!==s.reference?`${sources.at(-1)?.reference}–`:''}{s.reference} · coleta {new Date(s.collectedAt).toLocaleDateString('pt-BR')}</span>:null;})}</p>;}
export function MetricTable({rows,title,groups=false}:{rows:EducationMetric[];title:string;groups?:boolean}){return rows.length?<div className="table-wrap"><table><caption>{title}</caption><thead><tr><th>Etapa</th><th>Indicador / grupo</th><th>Valor</th><th>Ano</th><th>Rede</th></tr></thead><tbody>{rows.map(r=><tr key={[r.sourceId,r.stage,r.metric,r.reference].join('-')}><th scope="row">{r.stage}</th><td>{metricLabels[r.metric]??(groups?`Grupo ${r.metric.slice(-1)}`:r.metric)}</td><td>{format(r.value,r.unit==='IDEB'?'':r.unit)}</td><td>{r.reference}</td><td>{r.network}</td></tr>)}</tbody></table></div>:<p className="notice">Não há valores divulgados/integrados para este recorte. Ausência não equivale a zero.</p>;}
export function Comparison({data,network='Pública'}:{data:EducationData;network?:string}){
 const codes:Record<string,string>={'4127965':'Turvo','4119608':'Pitanga','4113254':'Laranjal','4109401':'Guarapuava','41':'Paraná'};
 const idebReference=latest(data.indicators.filter(r=>r.code==='4127965'&&r.network===network),'ideb','Anos iniciais')?.reference;
 function value(code:string,stage:string){const row=data.indicators.find(r=>r.code===code&&r.metric==='ideb'&&r.location==='Total'&&r.network===network&&r.stage===stage&&r.reference===idebReference);return row?.value;}
 return <Section id="edu-comparison" title="Turvo em perspectiva" description={`IDEB ${idebReference??'não disponível'} · rede ${network.toLowerCase()} · comparação entre a mesma etapa, rede e referência.`}><p>Números absolutos de matrículas também refletem o tamanho dos municípios. Esta comparação apresenta etapas separadas e não calcula um IDEB geral.</p><div className="table-wrap"><table><caption>IDEB · mesma rede e período</caption><thead><tr><th>Território</th><th>Anos iniciais</th><th>Anos finais</th><th>Ensino médio regular</th></tr></thead><tbody>{Object.entries(codes).map(([code,name])=><tr key={code} className={code==='4127965'?'edu-highlight':''}><th scope="row">{name}<small>{code==='41'?'UF 41':`IBGE ${code}`}</small></th><td>{format(value(code,'Anos iniciais'))}</td><td>{format(value(code,'Anos finais'))}</td><td>{format(value(code,'Ensino médio'))}</td></tr>)}</tbody></table></div><p className="edu-muted">Não divulgado inclui ausência de resultado ou recorte incompatível. Metas do primeiro ciclo do IDEB terminam em 2021 e não são interpretadas como metas para 2025.</p><SourceNote data={data} keys={['ideb']}/></Section>;
}
export function Methodology({data}:{data:EducationData}){return <Section id="edu-sources" title="Fontes e metodologia"><div className="edu-method"><article><h3>Censo Escolar</h3><p>Matrículas, escolas, docentes e turmas segundo os agregados públicos do INEP. Contamos escolas em atividade com matrículas da educação básica informadas, no universo da Sinopse. Educação especial atravessa diferentes etapas; educação profissional também pode se sobrepor ao ensino médio e EJA. Não somamos esses recortes ao total.</p></article><article><h3>Aprendizagem e fluxo</h3><p>IDEB combina desempenho no SAEB e fluxo escolar, por etapa e rede. Proficiência SAEB usa escala própria e não é percentual de acertos. Aprovação, reprovação e abandono descrevem fluxo; abandono não é uma medida longitudinal de evasão.</p></article></div><p>Todos os recortes mostram sua rede. “Todas as redes” inclui escolas sob administrações diferentes. A rede municipal considera apenas escolas municipais; alfabetização usa o resultado divulgado para essa rede. Não atribuímos indicadores estaduais à Prefeitura.</p><p>Não publicamos informações individuais de estudantes ou docentes, nem reconstruímos resultados suprimidos. Valores ausentes ficam sem valor; zeros são mantidos somente quando divulgados ou confirmados por cobertura completa.</p><p>Distorção idade-série: estudantes com idade dois anos ou mais acima da esperada para a série, segundo o indicador INEP. Docências somadas por escola podem contar a mesma pessoa em escolas diferentes; não equivalem a docentes únicos do município. Formação superior e adequação à disciplina são indicadores distintos.</p><p>Regularidade docente descreve a permanência dos docentes nas escolas; esforço docente considera escolas, turnos, alunos e etapas. Esses indicadores não classificam a qualidade de um professor. Tempo integral utiliza o campo oficial, sem inferência por horas-aula.</p><details><summary>Proveniência dos arquivos e limitações</summary><p>Território IBGE 4127965; UF PR. CSVs escolares: código INEP CO_ENTIDADE. Dados coletados em {data.collection.attemptedAt?new Date(data.collection.attemptedAt).toLocaleDateString('pt-BR'):'data não disponível'}. Cada observação no JSON registra rede, etapa, unidade, coluna de origem, referência e fonte.</p>{data.sources.map(s=><article key={s.id}><h4>{s.label||s.key} · {s.reference}</h4><a href={s.url} target="_blank" rel="noreferrer">Arquivo oficial INEP ↗</a><p>{s.format} · {format(s.bytes)} bytes</p><code>{s.sha256}</code></article>)}{data.limitations.map(l=><p key={l}>{l}</p>)}</details><h3>Baixar dados de Educação</h3><div className="edu-downloads">{['education.json','education-enrolments.csv','education-ideb.csv','education-flow.csv','education-schools.csv','education-infrastructure.csv','education-indicators.csv'].map(file=><a key={file} href={dataUrl(file.endsWith('.csv')?'exports/'+file:file)} download>{file} ↓</a>)}</div></Section>;}
