import {useEffect,useState} from 'react';
import {BookOpen,Download,School as SchoolIcon} from 'lucide-react';
import type {EducationData} from './types';
import {loadEducation,labels,format,latest,narrative,dataUrl} from './data';
import {Section,SourceNote,MetricTable,Comparison,Methodology} from './EducationComponents';
import {EducationChart} from './EducationCharts';
import './education.css';
const stages=['Educação básica','Educação infantil','Creche','Pré-escola','Ensino fundamental','Anos iniciais','Anos finais','Ensino médio','EJA'];
const sections=[['edu-summary','Panorama'],['edu-enrolments','Matrículas'],['edu-networks','Redes'],['edu-learning','Aprendizagem'],['edu-literacy','Alfabetização'],['edu-flow','Fluxo'],['edu-teachers','Professores'],['edu-infrastructure','Estrutura'],['edu-schools','Escolas'],['edu-sources','Fontes']];
export default function EducationPage({comparisonOnly=false}:{comparisonOnly?:boolean}){
 const [data,setData]=useState<EducationData>(),[error,setError]=useState(''),[retry,setRetry]=useState(0),[network,setNetwork]=useState('Total'),[learningNetwork,setLearningNetwork]=useState('Pública'),[query,setQuery]=useState(''),[activeOnly,setActiveOnly]=useState(true);
 useEffect(()=>{const controller=new AbortController();setError('');setData(undefined);loadEducation(controller.signal).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[retry]);
 if(error)return <section className="panel" role="alert"><h2>Educação indisponível</h2><p>{error}</p><button onClick={()=>setRetry(n=>n+1)}>Tentar novamente</button></section>;
 if(!data)return <div role="status" className="loading">Carregando Educação…<div className="skeleton"/></div>;
 if(comparisonOnly)return <div className="education-page"><Comparison data={data}/></div>;
 const reference=data.census.reference,census=data.census.series.find(r=>r.code==='4127965'&&r.network===network&&r.reference===reference),all=data.census.series.find(r=>r.code==='4127965'&&r.network==='Total'&&r.reference===reference),annual=data.census.series.filter(r=>r.code==='4127965'&&r.network===network);
 const metrics=data.indicators.filter(r=>r.code==='4127965'&&r.location==='Total'&&r.network===network),learning=data.indicators.filter(r=>r.code==='4127965'&&r.location==='Total'&&r.network===learningNetwork&&r.metric==='ideb');
 const recent=(k:string)=>{const rows=metrics.filter(r=>r.metric.startsWith(k));const year=rows.map(r=>r.reference).sort().at(-1);return rows.filter(r=>r.reference===year&&stages.includes(r.stage));};
 const networkSeries=[{key:'Municipal',label:'Municipal',color:'#1d5748'},{key:'Estadual',label:'Estadual',color:'#6b9d8d'},{key:'Privada',label:'Privada',color:'#c69642'},{key:'Federal',label:'Federal',color:'#5c7896'}].filter(s=>network==='Total'||s.key===network);
 const stageRows=['nursery','preschool','initial','final','secondary','eja'].map(k=>({period:labels[k],...Object.fromEntries(networkSeries.map(s=>[s.key,data.census.series.find(r=>r.code==='4127965'&&r.reference===reference&&r.network===s.key)?.enrolments[k]??null]))}));
 const flow=recent('flow');const flowChart=stages.map(period=>{const r=flow.filter(r=>r.stage===period);return {period,approval:r.find(r=>r.metric==='flowApproval')?.value??null,repetition:r.find(r=>r.metric==='flowRepetition')?.value??null,dropout:r.find(r=>r.metric==='flowDropout')?.value??null};}).filter(r=>r.approval!=null&&r.repetition!=null&&r.dropout!=null);
 const idebAI=latest(learning,'ideb','Anos iniciais'),idebAF=latest(learning,'ideb','Anos finais');
 const years=[...new Set(learning.map(r=>r.reference))].sort();const idebSeries=years.map(period=>({period,initial:learning.find(r=>r.reference===period&&r.stage==='Anos iniciais')?.value??null,final:learning.find(r=>r.reference===period&&r.stage==='Anos finais')?.value??null,secondary:learning.find(r=>r.reference===period&&r.stage==='Ensino médio')?.value??null}));
 const literacy=data.indicators.filter(r=>r.code==='4127965'&&r.location==='Total'&&r.network==='Municipal'&&r.metric==='literacy');
 const schools=data.schools.filter(s=>s.municipalityCode==='4127965'&&(network==='Total'||s.network===network)&&(!activeOnly||s.active)&&s.name.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')));
 return <div className="education-page"><div className="edu-intro"><div><span className="eyebrow"><BookOpen size={16}/> EDUCAÇÃO EM NÚMEROS</span><h2>Das primeiras letras<br/>às trajetórias de aprendizagem.</h2><p>Matrículas, escolas e indicadores oficiais para conhecer a educação básica de Turvo.</p></div><a className="edu-download" href={dataUrl('education.json')} download><Download size={15}/> Baixar dados de Educação</a></div>{data.collection.failures.length>0&&<div className="notice" role="status">A última coleta teve falhas; os últimos dados validados foram preservados.<details><summary>Ver relatório</summary>{data.collection.failures.map(f=><p key={f}>{f}</p>)}</details></div>}<nav className="edu-nav" aria-label="Seções de Educação">{sections.map(([id,name])=><button key={id} onClick={()=>document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})}>{name}</button>)}</nav><div className="edu-filters"><label>Rede educacional <select value={network} onChange={e=>setNetwork(e.target.value)}>{['Total','Municipal','Estadual','Privada','Federal'].map(n=><option key={n} value={n}>{n==='Total'?'Todas as redes':`Rede ${n.toLowerCase()}`}</option>)}</select></label><p>Filtro aplicado ao Censo, indicadores anuais, escolas e infraestrutura. IDEB tem seleção própria; alfabetização mostra a rede municipal.</p></div>
 <section id="edu-summary"><div className="section-title"><h2>Educação em números</h2><span>Censo Escolar {reference??'não disponível'}</span></div><div className="edu-cards">{[{title:'Matrículas registradas',value:census?.enrolments.total,note:network==='Total'?'Todas as redes':`Rede ${network.toLowerCase()}`,year:reference},{title:'Escolas em atividade',value:census?.activeSchools,note:'Situação oficial de funcionamento',year:reference},{title:'IDEB · anos iniciais',value:idebAI?.value,note:`Rede ${learningNetwork.toLowerCase()}`,year:idebAI?.reference},{title:'IDEB · anos finais',value:idebAF?.value,note:`Rede ${learningNetwork.toLowerCase()}`,year:idebAF?.reference},{title:'Aprovação · anos iniciais',value:latest(metrics,'flowApproval','Anos iniciais')?.value,unit:'%',note:network==='Total'?'Todas as redes':network,year:latest(metrics,'flowApproval','Anos iniciais')?.reference},{title:'Docentes com curso superior · AI',value:latest(metrics,'dsu','Anos iniciais')?.value,unit:'%',note:network==='Total'?'Todas as redes':network,year:latest(metrics,'dsu','Anos iniciais')?.reference}].map(c=><article className="edu-card" key={c.title}><span>{c.title}</span><strong>{format(c.value,c.unit)}</strong>{c.unit==='%'&&c.value!=null&&<progress max={100} value={c.value} aria-label={c.title}/>}<p>{c.note}</p><small>{c.year??'Não disponível'} · INEP</small></article>)}</div><p className="edu-callout">{narrative(census?.enrolments.total,reference,network)}</p></section>
 <Section id="edu-enrolments" title="Matrículas: acesso e evolução" description={`${network==='Total'?'Todas as redes':`Rede ${network.toLowerCase()}`} · série de agregados escolares, sem estudantes individuais.`}><EducationChart title="Evolução das matrículas em Turvo" rows={annual.map(r=>({period:r.reference,total:r.enrolments.total,infant:r.enrolments.infant,fundamental:r.enrolments.fundamental,secondary:r.enrolments.secondary}))} series={[{key:'total',label:'Educação básica',color:'#1d5748'},{key:'infant',label:'Educação infantil',color:'#c69642'},{key:'fundamental',label:'Ensino fundamental',color:'#6b9d8d'},{key:'secondary',label:'Ensino médio',color:'#5c7896'}]}/><h3>Onde estão as matrículas? · {reference}</h3><EducationChart bars stacked title="Matrículas por etapa e rede" rows={stageRows} series={networkSeries}/><div className="edu-two"><article><h3>Educação profissional</h3><strong>{format(census?.enrolments.professional)} matrículas</strong><p>Recorte que pode se sobrepor ao ensino médio e EJA. Não é somado às etapas para reconstruir o total.</p></article><article><h3>Educação especial</h3><strong>{format(census?.enrolments.special)} matrículas</strong><p>Inclui estudantes em classes comuns ou exclusivas, atravessando etapas. Não é uma etapa independente.</p></article></div><p>Tempo integral, conforme o campo oficial: <strong>{format(census?.enrolments.fullTime)} matrículas</strong>{census?.enrolments.fullTime!=null&&census.enrolments.total?` (${format(census.enrolments.fullTime/census.enrolments.total*100,'%')})`:''}. Não inferimos essa condição a partir da média de horas-aula.</p><SourceNote data={data} keys={['census']}/></Section>
 <Section id="edu-networks" title="Rede educacional e território" description="Município de Turvo e rede municipal são universos diferentes."><div className="table-wrap"><table><caption>Censo Escolar {reference} · escolas ativas por dependência</caption><thead><tr><th>Rede</th><th>Escolas</th><th>Matrículas</th><th>Participação nas matrículas</th><th>Docências somadas por escola</th><th>Turmas</th></tr></thead><tbody>{data.census.series.filter(r=>r.code==='4127965'&&r.reference===reference&&r.network!=='Total').map(r=><tr key={r.network} className={r.network==='Municipal'?'edu-highlight':''}><th scope="row">{r.network}</th><td>{format(r.activeSchools)}</td><td>{format(r.enrolments.total)}</td><td>{r.enrolments.total!=null&&all?.enrolments.total?format(r.enrolments.total/all.enrolments.total*100,'%'):'Não divulgado'}</td><td>{format(r.teachingPosts)}</td><td>{format(r.classes)}</td></tr>)}</tbody></table></div><h3>Educação no território · {network==='Total'?'todas as redes':network}</h3><div className="edu-two">{census?.locations.map(l=><article key={l.label}><SchoolIcon size={20}/><h3>{l.label}</h3><p><strong>{format(l.schools)}</strong> escolas em atividade · <strong>{format(l.enrolments)}</strong> matrículas</p></article>)}</div><p className="edu-muted">Localização é a classificação oficial da escola. Uma pessoa que ensina em duas escolas pode aparecer duas vezes na soma de docências. Não contamos docentes municipais únicos a partir dessa soma.</p><SourceNote data={data} keys={['census']}/></Section>
 <Section id="edu-learning" title="Aprendizagem: IDEB e SAEB" description="Resultados divulgados por etapa e rede. Não existe um IDEB geral calculado pelo observatório."><label className="edu-select">Rede para IDEB e comparação <select value={learningNetwork} onChange={e=>setLearningNetwork(e.target.value)}>{['Pública','Municipal','Estadual'].map(n=><option key={n}>{n}</option>)}</select></label><p>O Índice de Desenvolvimento da Educação Básica combina desempenho e fluxo escolar. Os anos iniciais registraram {format(idebAI?.value)} em {idebAI?.reference??'período não disponível'}, na rede {learningNetwork.toLowerCase()}.</p><EducationChart title="Evolução do IDEB de Turvo" unit="IDEB" rows={idebSeries} series={[{key:'initial',label:'Anos iniciais',color:'#1d5748'},{key:'final',label:'Anos finais',color:'#c69642'},{key:'secondary',label:'Ensino médio regular',color:'#5c7896'}]}/><p className="edu-muted">Lacunas não são ligadas por linhas. Metas do primeiro ciclo até 2021 não são comparadas como metas atuais.</p><h3>SAEB · proficiência média</h3><p>Filtro de rede: {network==='Total'?'todas as redes':network}. Língua Portuguesa e Matemática aparecem separadas. A escala não representa percentual de acertos. Ausentes/suprimidos aparecem como “Não divulgado”; a publicação municipal segue os critérios do INEP.</p><MetricTable title="Proficiência municipal SAEB" rows={metrics.filter(r=>r.unit==='pontos SAEB')}/><SourceNote data={data} keys={['ideb','saeb']}/></Section>
 <Section id="edu-literacy" title="Alfabetização" description="Indicador Criança Alfabetizada · 2º ano do ensino fundamental · rede municipal."><div className="edu-two"><article><span>Resultado mais recente</span><strong className="edu-number">{format(latest(literacy,'literacy')?.value,'%')}</strong><p>Referência: {latest(literacy,'literacy')?.reference??'não disponível'}</p></article><article><span>Meta oficial / participação</span><strong className="edu-number">{format(latest(data.indicators.filter(r=>r.code==='4127965'),'literacyTarget')?.value,'%')}</strong><p>Participação: {format(latest(data.indicators.filter(r=>r.code==='4127965'),'literacyParticipation')?.value,'%')}</p></article></div><MetricTable title="Histórico de alfabetização · rede municipal" rows={literacy}/><p>Resultado de avaliação articulada aos sistemas estaduais, divulgado pelo INEP. Não é IDEB e não representa todas as crianças residentes no município.</p><SourceNote data={data} keys={['literacy']}/></Section>
 <Section id="edu-flow" title="Fluxo escolar" description="Aprovação, reprovação e abandono · indicadores de rendimento, por etapa.">{flowChart.length>0&&<EducationChart bars stacked unit="%" title="Fluxo escolar por etapa" rows={flowChart} series={[{key:'approval',label:'Aprovação',color:'#1d5748'},{key:'repetition',label:'Reprovação',color:'#c69642'},{key:'dropout',label:'Abandono',color:'#8f6571'}]}/>}<MetricTable rows={flow} title="Taxas de rendimento escolar"/><p>Aprovação não é sinônimo de qualidade da educação. Abandono tem a definição anual deste indicador e não equivale automaticamente à evasão longitudinal. A soma das três taxas é conferida quando o universo é o mesmo, com tolerância de arredondamento.</p><SourceNote data={data} keys={['flow']}/><h3>Distorção idade-série</h3><p>Percentual de estudantes com idade dois anos ou mais acima da esperada para a série, conforme definição INEP.</p><MetricTable rows={recent('tdi')} title="Distorção idade-série"/><SourceNote data={data} keys={['tdi']}/></Section>
 <Section id="edu-teachers" title="Professores: formação e condições" description="Percentuais oficiais por etapa e rede; formação e esforço medem conceitos distintos."><div className="edu-callout"><strong>Docentes da educação básica: {format(census?.teachersOfficial)}</strong> · {reference} · {network==='Total'?'todas as redes':network}. Contagem oficial da Sinopse, deduplicada no universo municipal/rede informado. Não somamos redes para reconstruir docentes únicos.</div><SourceNote data={data} keys={['synopsis']}/><h3>Docentes com curso superior</h3><MetricTable rows={recent('dsu')} title="Percentual de docentes com curso superior"/><h3>Adequação da formação docente</h3><p>Grupo 1: licenciatura na disciplina lecionada ou bacharelado na mesma disciplina com complementação pedagógica. Os demais grupos permanecem separados; não calculamos uma média entre eles.</p><MetricTable rows={recent('afd')} title="Adequação da formação · grupos 1 a 5" groups/><details><summary>Condições do trabalho docente</summary><h3>Esforço docente</h3><p>Distribuição nos seis grupos oficiais, considerando alunos, escolas, turnos e etapas. Não é uma classificação da qualidade dos professores.</p><MetricTable rows={recent('ied')} title="Esforço docente · grupos oficiais" groups/><h3>Regularidade do corpo docente</h3><p>Descreve permanência dos docentes nas escolas no período observado. Mantemos a distribuição oficial de escolas por faixa, sem atribuir avaliação individual.</p><MetricTable rows={recent('ird')} title="Regularidade docente · grupos oficiais" groups/></details><SourceNote data={data} keys={['dsu','afd','ied','ird']}/></Section>
 <Section id="edu-conditions" title="Condições de ensino" description="Médias oficiais por etapa. Não representam limites máximos de turma ou jornada integral."><h3>Média de alunos por turma</h3><MetricTable rows={recent('atu')} title="Média de alunos por turma"/><h3>Tempo diário de aula</h3><MetricTable rows={recent('had')} title="Média de horas-aula diárias"/><SourceNote data={data} keys={['atu','had']}/></Section>
 <Section id="edu-infrastructure" title="Estrutura das escolas" description={`${network==='Total'?'Todas as redes':`Rede ${network.toLowerCase()}`} · escolas em atividade · Censo ${reference}. Cada recurso tem seu próprio denominador.`}><div className="edu-resources">{data.infrastructure.filter(r=>r.code==='4127965'&&r.network===network).map(r=><article key={r.id}><div><strong>{r.label}</strong><span>{format(r.percent,'%')}</span></div>{r.percent!=null&&<progress max={100} value={r.percent} aria-label={r.label}/>}<small>{r.withResource} de {r.considered} escolas com informação válida · {r.missing} sem informação · {r.activeSchools} ativas</small></article>)}</div><details><summary>Ver infraestrutura em tabela acessível</summary><div className="table-wrap"><table><caption>Recursos por escola · {reference} · {network}</caption><thead><tr><th>Recurso</th><th>Com recurso</th><th>Consideradas</th><th>Sem informação</th><th>Ativas</th><th>Percentual</th></tr></thead><tbody>{data.infrastructure.filter(r=>r.code==='4127965'&&r.network===network).map(r=><tr key={r.id}><th scope="row">{r.label}</th><td>{r.withResource}</td><td>{r.considered}</td><td>{r.missing}</td><td>{r.activeSchools}</td><td>{format(r.percent,'%')}</td></tr>)}</tbody></table></div></details><p className="edu-muted">Sem denominador, percentual não é divulgado. Água, energia e esgoto distinguem os campos específicos do Censo. Não criamos um índice composto de infraestrutura.</p><SourceNote data={data} keys={['census']}/></Section>
 <Section id="edu-schools" title="Escolas de Turvo" description="Catálogo institucional por código INEP, com rede, localização e situação de funcionamento."><div className="edu-filters"><label>Buscar escola <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nome da escola"/></label><label className="edu-check"><input type="checkbox" checked={activeOnly} onChange={e=>setActiveOnly(e.target.checked)}/> Somente escolas em atividade</label></div><p>{schools.length} {schools.length===1?'escola':'escolas'} neste recorte.</p><div className="table-wrap"><table><caption>Catálogo de escolas · {reference}</caption><thead><tr><th>Escola / INEP</th><th>Rede</th><th>Localização</th><th>Situação</th><th>Etapas/modalidades com matrículas</th></tr></thead><tbody>{schools.map(s=><tr key={s.code}><th scope="row">{s.name}<small>{s.code}</small></th><td>{s.network}</td><td>{s.location}</td><td>{s.situation}{!s.inBasicEducationUniverse&&<small>Fora do universo de matrículas da educação básica</small>}</td><td>{s.stages.map(k=>labels[k]).join(' · ')||'Não informado'}</td></tr>)}</tbody></table></div><SourceNote data={data} keys={['census']}/></Section><Comparison data={data} network={learningNetwork}/><Methodology data={data}/></div>;
}
