import { lazy, Suspense, useEffect, useState } from 'react';
import { ArrowDownToLine, ArrowRight, ChartNoAxesCombined, MapPin, Menu, Search, X, ExternalLink } from 'lucide-react';
import {modules, type ModuleId} from './modules/catalog';
import {loadData} from './lib/data';
import type {Dataset} from './lib/types';
import {DataTable, IndicatorCard, SeriesChart} from './components/Indicators';
const EnvironmentPage = lazy(() => import('./modules/environment/EnvironmentPage'));
const SocialAssistancePage = lazy(() => import('./modules/social/SocialAssistancePage'));
const AgriculturePage = lazy(() => import('./modules/agriculture/AgriculturePage'));
const EconomyPage = lazy(() => import('./modules/economy/EconomyPage'));
const HealthPage = lazy(() => import('./modules/health/HealthPage'));
const EducationPage = lazy(() => import('./modules/education/EducationPage'));
const EmploymentPage = lazy(() => import('./modules/employment/EmploymentPage'));
const PopulationPage = lazy(() => import('./modules/population/PopulationPage'));
function route(): ModuleId { const id=location.hash.slice(1); return modules.some(m=>m[0]===id) ? id as ModuleId : 'overview'; }
export function App() {
 const [active,setActive]=useState<ModuleId>(route),[data,setData]=useState<Dataset>(),[error,setError]=useState(''),[retry,setRetry]=useState(0),[open,setOpen]=useState(false),[query,setQuery]=useState('');
 useEffect(()=>{const update=()=>{setActive(route());setOpen(false);setQuery('');};window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);
 useEffect(()=>{const controller=new AbortController(); setError('');setData(undefined);loadData(controller.signal).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[retry]);
 const current=modules.find(m=>m[0]===active)!;
 const indicators=data?.indicators??[];const shown=indicators.filter(i=>active==='overview'?i.status==='real':i.module===active);
 if(active==='overview') shown.sort((a,b)=>['population-estimate','population-census','gdp','territorial-area','population-density'].indexOf(a.id)-['population-estimate','population-census','gdp','territorial-area','population-density'].indexOf(b.id));
 const official=indicators.filter(i=>i.status==='real').length;
 return <div className="app"><a className="skip" href="#content">Pular para o conteúdo</a><aside className={open?'sidebar open':'sidebar'}><a className="brand" href="#overview" aria-label="Observatório de Turvo — Visão Geral"><img className="brand-logo" src={`${import.meta.env.BASE_URL}branding/turvo-logo.png`} alt="Prefeitura Municipal de Turvo" width={160} height={160}/><span>OBSERVATÓRIO MUNICIPAL</span></a><div className="side-label">EXPLORAR O MUNICÍPIO</div><nav aria-label="Módulos do observatório">{modules.map(([id,label],index)=><a href={`#${id}`} key={id} className={active===id?'selected':''} aria-current={active===id?'page':undefined}><span className="nav-number">{String(index+1).padStart(2,'0')}</span>{label}{active===id&&<ArrowRight size={15}/>}</a>)}</nav><div className="side-foot"><span className="dot"/> Dados públicos, conhecimento aberto<p>Projeto independente · Código aberto<br/>Município IBGE 4127965</p></div></aside>{open&&<button className="overlay" aria-label="Fechar menu" onClick={()=>setOpen(false)}/>}<div className="main"><header className="topbar"><button className="menu-button" onClick={()=>setOpen(!open)} aria-label={open?'Fechar navegação':'Abrir navegação'} aria-expanded={open}>{open?<X/>:<Menu/>}</button><span><MapPin size={15}/> Turvo, Paraná <span className="desktop">/ Região de Guarapuava</span></span><a href={`${import.meta.env.BASE_URL}data/indicators.json`} download><ArrowDownToLine size={15}/> Baixar dados</a></header><main id="content"><div className="breadcrumb">Observatório Municipal <span>/</span> {current[1]}</div><section className="page-title"><div><span className="eyebrow">TERRITÓRIO EM NÚMEROS</span><h1>{current[1]}</h1><p>{current[2]}. Informação aberta para entender e acompanhar Turvo.</p></div><span className="location-pill"><MapPin size={15}/> Turvo / PR</span></section>{error?<section className="panel" role="alert"><h2>Os dados não carregaram</h2><p>{error}</p><button onClick={()=>setRetry(x=>x+1)}>Tentar novamente</button></section>:!data?<div role="status" className="loading">Carregando indicadores…<div className="skeleton"/></div>:<>
 {active==='overview'&&<section className="hero"><div><span className="eyebrow">OLHAR LOCAL. DADOS ABERTOS.</span><h2>Conhecer o território<br/>é o primeiro passo.</h2><p>Explore indicadores, consulte as fontes e acompanhe as transformações do nosso município.</p><a href="#catalog">Explorar catálogo de dados <ArrowRight size={16}/></a></div><div className="hero-art" aria-hidden="true"><div className="ring ring-one"/><div className="ring ring-two"/><ChartNoAxesCombined size={82}/><span>25° S · 51° O</span></div></section>}
 {active!=='about'&&active!=='population'&&active!=='economy'&&active!=='employment'&&active!=='education'&&active!=='health'&&active!=='agriculture'&&active!=='social'&&active!=='environment'&&<div className="section-title"><h2>{active==='overview'?'Indicadores em destaque':active==='catalog'?'Dados disponíveis':'Indicadores do módulo'}</h2><span>{official} indicadores oficiais no catálogo</span></div>}
 {['overview','finance'].includes(active)&&<><div className="cards">{shown.map(i=><IndicatorCard key={i.id} item={i}/>)}</div>{shown.some(i=>i.status!=='real')&&<div className="notice">Este módulo está em desenvolvimento. Valores marcados como demonstração são fictícios e não devem ser usados para decisões.</div>}<div className="chart-grid">{shown.filter(i=>i.series.length>1).slice(0,2).map(i=><SeriesChart key={i.id} item={i}/>)}</div>{shown.length>0&&<section className="panel"><h2>Dados e referências</h2><DataTable items={shown}/></section>}<section className="panel next"><div><span className="eyebrow">EVOLUÇÃO DO MÓDULO</span><h2>{active==='overview'?'Um observatório em construção':'Próximas entregas'}</h2><p>{active==='overview'?'Explore as áreas temáticas. Cada indicador mantém sua fonte e referência temporal.':'TODO: ampliar séries históricas, validar conceitos e cobertura, integrar novas fontes e documentar revisões.'}</p></div><a href="#about">Conheça a metodologia <ArrowRight size={16}/></a></section></>}
 {active==='environment'&&<Suspense fallback={<div role="status">Carregando Meio Ambiente…</div>}><EnvironmentPage/></Suspense>}
 {active==='social'&&<Suspense fallback={<div role="status">Carregando Assistência Social…</div>}><SocialAssistancePage/></Suspense>}
 {active==='agriculture'&&<Suspense fallback={<div role="status">Carregando Agropecuária…</div>}><AgriculturePage/></Suspense>}
 {active==='health'&&<Suspense fallback={<div role="status">Carregando Saúde…</div>}><HealthPage/></Suspense>}
 {active==='education'&&<Suspense fallback={<div role="status">Carregando Educação…</div>}><EducationPage/></Suspense>}
 {active==='employment'&&<Suspense fallback={<div role="status">Carregando Trabalho e Emprego…</div>}><EmploymentPage/></Suspense>}
 {active==='economy'&&<Suspense fallback={<div role="status">Carregando módulo Economia…</div>}><EconomyPage/></Suspense>}
 {active==='population'&&<Suspense fallback={<div role="status">Carregando módulo População…</div>}><PopulationPage/></Suspense>}
 {active==='catalog'&&<section className="panel"><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar indicador, fonte ou órgão" aria-label="Buscar no catálogo"/></label><DataTable items={indicators.filter(i=>`${i.title} ${i.source} ${i.agency}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')))}/><p><a href={`${import.meta.env.BASE_URL}data/indicators.json`} download>Baixar catálogo completo em JSON</a></p><div className="metadata-list">{indicators.filter(i=>`${i.title} ${i.source} ${i.agency}`.toLowerCase().includes(query.toLowerCase())).map(i=><details key={i.id}><summary>Metadados: {i.title}</summary><dl>{Object.entries({Fonte:i.source,Órgão:i.agency,Referência:i.reference,Unidade:i.unit,'Código IBGE':i.municipalityCode,Coleta:i.collectedAt??'Não coletado',URL:i.url,Observação:i.note??'Consulte a documentação da fonte.'}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></details>)}</div></section>}
 {active==='about'&&<><section className="panel prose"><h2>Transparência desde a origem</h2><p>O Observatório de Turvo é um projeto independente e open-source. Não representa um portal oficial da Prefeitura. Seu objetivo é facilitar o acesso a informações públicas sobre Turvo/PR, código IBGE 4127965.</p><h3>Como funciona</h3><p>Rotinas Python consultam as fontes públicas, validam município, variável, unidade e referência temporal e geram arquivos JSON. A aplicação consulta esses arquivos estáticos: não exige servidor ou banco de dados.</p><h3>Dados oficiais e demonstrações</h3><p>Dados oficiais são identificados como “Dado oficial”. Demonstrações têm números fictícios, sem data de coleta, e servem apenas para testar a interface. Indicadores não disponíveis aparecem sem valor.</p><h3>Atualização e falhas</h3><p>População e Economia têm coleta semanal preparada. Trabalho e Emprego usa atualização mensal do Novo CAGED e anual da RAIS. Assistência Social verifica publicações mensais do MDS e edições anuais do Censo SUAS/RMA, com referências independentes por fonte. Saúde verifica mensalmente as exportações oficiais do CNES, leitos e regiões. Educação verifica novas publicações mensalmente, com downloads por edição anual ou ciclo de avaliação. A referência do indicador pode ser anual ou censitária. Se uma fonte falhar, preservamos o último dado válido e registramos o problema; data de coleta não significa data de publicação.</p><h3>Comparabilidade e unidades</h3><p>O PIB do SIDRA em mil reais é convertido para reais. Valores são nominais, sem correção pela inflação. População censitária e estimativa populacional são conceitos distintos. Comparações exigem a mesma unidade e referência.</p><h3>Limites e evolução</h3><p>TODOs por módulo estão no roadmap do repositório. RAIS e Novo CAGED estão integrados com fontes oficiais e metodologia própria. Educação usa Censo Escolar, Sinopse, IDEB, SAEB, alfabetização e indicadores municipais do INEP. Meio Ambiente integra cobertura da terra, vegetação, focos de calor, cadastro de estações e áreas protegidas, com fontes e limitações próprias. SICONFI ainda exige conector e validação da metodologia. Não agregamos microdados pessoais.</p><a href="https://github.com/Alantratch/observatorio-turvo-estatico" target="_blank" rel="noreferrer">Código, documentação e contribuições <ExternalLink size={14}/></a></section></>}
 {data.collection.failures.length>0&&<div className="notice">Última tentativa com falhas em {data.collection.failures.length} consulta(s). Os últimos dados disponíveis foram preservados. Consulte o relatório no catálogo JSON.</div>}
 </>}<footer><span>Observatório de Turvo / PR <b>·</b> Informação pública, acesso livre.</span><a href="#about">Fontes e metodologia <ArrowUpIcon/></a></footer></main></div></div>;
}
function ArrowUpIcon(){return <ExternalLink size={13}/>;}
