import { lazy, Suspense, useEffect, useState } from 'react';
import { ArrowDownToLine, ArrowRight, ChartNoAxesCombined, MapPin, Menu, Search, X, ExternalLink } from 'lucide-react';
import {modules, type ModuleId} from './modules/catalog';
import {loadData, format} from './lib/data';
import type {Dataset, Indicator} from './lib/types';
import {DataTable, IndicatorCard, SeriesChart} from './components/Indicators';
const PopulationPage = lazy(() => import('./modules/population/PopulationPage'));
function matchingPeer(current: Indicator, peer: Indicator) {
 const aliases: Record<string,string> = {'population-census':'population', 'population-density':'density', 'territorial-area':'area'};
 const sameId = peer.id === current.id || peer.id === aliases[current.id];
 // Existing peer snapshots explicitly identify table 4714 (Censo 2022).
 // An annual estimate or a different territorial edition cannot match this census bridge.
 const sameMethod = current.module !== 'population' ||
   (Boolean(current.methodology) && peer.methodology === current.methodology) ||
   (current.methodology === 'census' && ['population','density'].includes(peer.id) && peer.source.includes('4714'));
 return sameId && sameMethod && peer.reference === current.reference && peer.unit === current.unit && peer.status === 'real';
}
function route(): ModuleId { const id=location.hash.slice(1); return modules.some(m=>m[0]===id) ? id as ModuleId : 'overview'; }
export function App() {
 const [active,setActive]=useState<ModuleId>(route),[data,setData]=useState<Dataset>(),[error,setError]=useState(''),[retry,setRetry]=useState(0),[open,setOpen]=useState(false),[query,setQuery]=useState(''),[compare,setCompare]=useState('4109401');
 const [peers,setPeers]=useState<Record<string,{name:string;indicators:Dataset['indicators']}>>({});
 useEffect(()=>{const update=()=>{setActive(route());setOpen(false);setQuery('');};window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);
 useEffect(()=>{const controller=new AbortController(); setError('');setData(undefined);loadData(controller.signal).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[retry]);
 useEffect(()=>{const controller=new AbortController();fetch(`${import.meta.env.BASE_URL}data/comparison.json`,{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(setPeers).catch(()=>{});return()=>controller.abort();},[]);
 const current=modules.find(m=>m[0]===active)!;
 const indicators=data?.indicators??[];const shown=indicators.filter(i=>active==='overview'?i.status==='real':i.module===active);
 if(active==='overview') shown.sort((a,b)=>['population-estimate','population-census','gdp','territorial-area','population-density'].indexOf(a.id)-['population-estimate','population-census','gdp','territorial-area','population-density'].indexOf(b.id));
 const official=indicators.filter(i=>i.status==='real').length;
 return <div className="app"><a className="skip" href="#content">Pular para o conteúdo</a><aside className={open?'sidebar open':'sidebar'}><a className="brand" href="#overview"><span className="brand-icon"><ChartNoAxesCombined/></span><div>OBSERVATÓRIO<strong>Turvo<span> / PR</span></strong></div></a><div className="side-label">EXPLORAR O MUNICÍPIO</div><nav aria-label="Módulos do observatório">{modules.map(([id,label],index)=><a href={`#${id}`} key={id} className={active===id?'selected':''} aria-current={active===id?'page':undefined}><span className="nav-number">{String(index+1).padStart(2,'0')}</span>{label}{active===id&&<ArrowRight size={15}/>}</a>)}</nav><div className="side-foot"><span className="dot"/> Dados públicos, conhecimento aberto<p>Projeto independente · Código aberto<br/>Município IBGE 4127965</p></div></aside>{open&&<button className="overlay" aria-label="Fechar menu" onClick={()=>setOpen(false)}/>}<div className="main"><header className="topbar"><button className="menu-button" onClick={()=>setOpen(!open)} aria-label={open?'Fechar navegação':'Abrir navegação'} aria-expanded={open}>{open?<X/>:<Menu/>}</button><span><MapPin size={15}/> Turvo, Paraná <span className="desktop">/ Região de Guarapuava</span></span><a href={`${import.meta.env.BASE_URL}data/indicators.json`} download><ArrowDownToLine size={15}/> Baixar dados</a></header><main id="content"><div className="breadcrumb">Observatório Municipal <span>/</span> {current[1]}</div><section className="page-title"><div><span className="eyebrow">TERRITÓRIO EM NÚMEROS</span><h1>{current[1]}</h1><p>{current[2]}. Informação aberta para entender e acompanhar Turvo.</p></div><span className="location-pill"><MapPin size={15}/> Turvo / PR</span></section>{error?<section className="panel" role="alert"><h2>Os dados não carregaram</h2><p>{error}</p><button onClick={()=>setRetry(x=>x+1)}>Tentar novamente</button></section>:!data?<div role="status" className="loading">Carregando indicadores…<div className="skeleton"/></div>:<>
 {active==='overview'&&<section className="hero"><div><span className="eyebrow">OLHAR LOCAL. DADOS ABERTOS.</span><h2>Conhecer o território<br/>é o primeiro passo.</h2><p>Explore indicadores, consulte as fontes e acompanhe as transformações do nosso município.</p><a href="#catalog">Explorar catálogo de dados <ArrowRight size={16}/></a></div><div className="hero-art" aria-hidden="true"><div className="ring ring-one"/><div className="ring ring-two"/><ChartNoAxesCombined size={82}/><span>25° S · 51° O</span></div></section>}
 {active!=='about'&&active!=='population'&&<div className="section-title"><h2>{active==='overview'?'Indicadores em destaque':active==='catalog'?'Dados disponíveis':active==='compare'?'Compare com municípios próximos':'Indicadores do módulo'}</h2><span>{official} indicadores oficiais no catálogo</span></div>}
 {['overview','economy','employment','education','health','finance','procurement','agriculture'].includes(active)&&<><div className="cards">{shown.map(i=><IndicatorCard key={i.id} item={i}/>)}</div>{shown.some(i=>i.status!=='real')&&<div className="notice">Este módulo está em desenvolvimento. Valores marcados como demonstração são fictícios e não devem ser usados para decisões.</div>}<div className="chart-grid">{shown.filter(i=>i.series.length>1).slice(0,2).map(i=><SeriesChart key={i.id} item={i}/>)}</div>{shown.length>0&&<section className="panel"><h2>Dados e referências</h2><DataTable items={shown}/></section>}<section className="panel next"><div><span className="eyebrow">EVOLUÇÃO DO MÓDULO</span><h2>{active==='overview'?'Um observatório em construção':'Próximas entregas'}</h2><p>{active==='overview'?'Explore as áreas temáticas. Cada indicador mantém sua fonte e referência temporal.':'TODO: ampliar séries históricas, validar conceitos e cobertura, integrar novas fontes e documentar revisões.'}</p></div><a href="#about">Conheça a metodologia <ArrowRight size={16}/></a></section></>}
 {active==='population'&&<Suspense fallback={<div role="status">Carregando módulo População…</div>}><PopulationPage/></Suspense>}
 {active==='catalog'&&<section className="panel"><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar indicador, fonte ou órgão" aria-label="Buscar no catálogo"/></label><DataTable items={indicators.filter(i=>`${i.title} ${i.source} ${i.agency}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')))}/><p><a href={`${import.meta.env.BASE_URL}data/indicators.json`} download>Baixar catálogo completo em JSON</a></p><div className="metadata-list">{indicators.filter(i=>`${i.title} ${i.source} ${i.agency}`.toLowerCase().includes(query.toLowerCase())).map(i=><details key={i.id}><summary>Metadados: {i.title}</summary><dl>{Object.entries({Fonte:i.source,Órgão:i.agency,Referência:i.reference,Unidade:i.unit,'Código IBGE':i.municipalityCode,Coleta:i.collectedAt??'Não coletado',URL:i.url,Observação:i.note??'Consulte a documentação da fonte.'}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></details>)}</div></section>}
 {active==='compare'&&<section className="panel"><label className="compare-select">Comparar Turvo com <select value={compare} onChange={e=>setCompare(e.target.value)}>{[['4109401','Guarapuava'],['4113254','Laranjal'],['4119608','Pitanga']].map(([id,name])=><option key={id} value={id}>{name} / PR</option>)}</select></label><p>Comparamos somente indicadores oficiais com a mesma referência temporal e unidade. PIB total reflete também o tamanho do município.</p><div className="table-wrap"><table><thead><tr><th>Indicador</th><th>Turvo</th><th>{peers[compare]?.name??'Município selecionado'}</th><th>Referência</th></tr></thead><tbody>{indicators.filter(i=>i.status==='real').map(i=>{const peer=peers[compare]?.indicators.find(p=>matchingPeer(i,p));return <tr key={i.id}><td>{i.title} ({i.unit})</td><td>{format(i.value,i.unit)}</td><td>{format(peer?.value??null,i.unit)}</td><td>{i.reference}{peer&&<> · <a href={peer.url} target="_blank" rel="noreferrer">Fonte comparada</a></>}</td></tr>;})}</tbody></table></div><p className="source">— indica dado indisponível ou referências incompatíveis. <a href={`${import.meta.env.BASE_URL}data/comparison.json`} download>Baixar dados comparados</a></p></section>}
 {active==='about'&&<><section className="panel prose"><h2>Transparência desde a origem</h2><p>O Observatório de Turvo é um projeto independente e open-source. Não representa um portal oficial da Prefeitura. Seu objetivo é facilitar o acesso a informações públicas sobre Turvo/PR, código IBGE 4127965.</p><h3>Como funciona</h3><p>Rotinas Python consultam as fontes públicas, validam município, variável, unidade e referência temporal e geram arquivos JSON. A aplicação consulta esses arquivos estáticos: não exige servidor ou banco de dados.</p><h3>Dados oficiais e demonstrações</h3><p>Dados oficiais são identificados como “Dado oficial”. Demonstrações têm números fictícios, sem data de coleta, e servem apenas para testar a interface. Indicadores não disponíveis aparecem sem valor.</p><h3>Atualização e falhas</h3><p>A coleta é programada semanalmente. A referência do indicador pode ser anual ou censitária. Se uma fonte falhar, preservamos o último dado válido e registramos o problema; data de coleta não significa data de publicação.</p><h3>Comparabilidade e unidades</h3><p>O PIB do SIDRA em mil reais é convertido para reais. Valores são nominais, sem correção pela inflação. População censitária e estimativa populacional são conceitos distintos. Comparações exigem a mesma unidade e referência.</p><h3>Limites e evolução</h3><p>TODOs por módulo estão no roadmap do repositório. RAIS/CAGED, INEP, DATASUS, SICONFI e PNCP exigem conectores próprios e validação das respectivas metodologias. Não agregamos microdados pessoais.</p><a href="https://github.com/Alantratch/observatorio-turvo-estatico" target="_blank" rel="noreferrer">Código, documentação e contribuições <ExternalLink size={14}/></a></section></>}
 {data.collection.failures.length>0&&<div className="notice">Última tentativa com falhas em {data.collection.failures.length} consulta(s). Os últimos dados disponíveis foram preservados. Consulte o relatório no catálogo JSON.</div>}
 </>}<footer><span>Observatório de Turvo / PR <b>·</b> Informação pública, acesso livre.</span><a href="#about">Fontes e metodologia <ArrowUpIcon/></a></footer></main></div></div>;
}
function ArrowUpIcon(){return <ExternalLink size={13}/>;}
